import { ApiError, getErrorMessage } from "@/lib/errors";
import type { Messages } from "@/i18n/LocaleContext";

/** The words of the courier settlements page (/settlements): what couriers hold, the settlements, and the two sheets. */
export const SETTLEMENT_STRINGS = {
  en: {
    title: "COD settlements",
    description: "Match the cash couriers collected on delivered orders with what they actually transferred to you.",
    answerDue: "Couriers still owe you {amount} for {orders} delivered.",
    answerClear: "No money is waiting with the couriers right now.",
    record: "Record a transfer",
    tools: "Settlement tools",
    importStatement: "Import a courier statement",
    importHint: "Match the courier's CSV file to your orders",
    refresh: "Refresh",
    refreshHint: "Ask again for what couriers hold and the settlements",

    kpiDue: "Due from couriers",
    kpiDueHint: "For {orders} delivered and not settled",
    kpiDueNone: "Nothing is waiting",
    kpiReceived: "Received",
    kpiReceivedHint: "Net of the confirmed settlements",
    kpiFees: "Courier fees",
    kpiFeesHint: "Taken off in the confirmed settlements",
    kpiDrafts: "Draft settlements",
    kpiDraftsHint: "Waiting for you to confirm",
    kpiDraftsNone: "No draft is waiting",

    viewLabel: "What the page shows",
    viewHeld: "With couriers",
    viewSettlements: "Settlements",

    heldLabel: "Money held, courier by courier",
    colCourier: "Courier",
    daysBand: "{from}–{to} days",
    daysOver: "Over {n} days",
    colTotal: "Total held",
    colAction: "Next step",
    ordersOldest: "{orders} · oldest delivery {date}",
    lateChip: "{amount} over {n} days",
    onTime: "Nothing over {n} days",
    inDraft: "In a draft, waiting to be confirmed",
    recordFor: "Record what {courier} paid you",
    noUnsettled: "No unsettled COD orders",
    noUnsettledDesc: "Delivered cash-on-delivery orders show up here until the courier pays you for them.",
    seeOrders: "See the orders",

    chipsLabel: "Settlements by status",
    chipAll: "All",
    chipDraft: "Drafts",
    chipConfirmed: "Confirmed",
    status_draft: "Draft",
    status_confirmed: "Confirmed",
    colDate: "Created",
    colStatus: "Status",
    colCollected: "Collected",
    colFees: "Fees",
    colNet: "Net",
    confirmShort: "Confirm",
    peek: "Open the settlement of {courier}, {date}",
    menuLabel: "Actions for this settlement",
    menuOpen: "Open the settlement",
    menuCopyRef: "Copy the reference",
    copiedRef: "The reference is copied",
    noSettlements: "No settlements yet",
    noSettlementsDesc: "A settlement records what a courier transferred to you for the orders it delivered.",
    noDrafts: "No draft is waiting to be confirmed",
    noConfirmed: "No settlement is confirmed yet",
    showAll: "Show all settlements",

    detailTitle: "Settlement · {carrier}",
    reference: "Reference",
    period: "Period",
    periodRange: "{from} – {to}",
    createdOn: "Created",
    confirmedOn: "Confirmed",
    notes: "Notes",
    linesTitle: "Orders in it",
    lineOf: "of",
    orderGone: "Deleted order",
    openOrder: "Open order {number}",
    confirm: "Confirm settlement",
    delete: "Delete draft",
    confirmTitle: "Confirm this settlement?",
    confirmDesc:
      "This records the collected amount as a payment on every order in it and marks them paid. A confirmed settlement can't be edited or deleted.",
    confirmed: "Settlement confirmed",
    deleteTitle: "Delete this draft?",
    deleteDesc: "The orders go back to the unsettled list. Nothing is recorded on them.",
    deleted: "Draft deleted",

    reconcileTitle: "Record a transfer",
    reconcileTitleFor: "What {courier} paid you",
    reconcileDesc: "Tick the orders the courier paid you for and fix an amount where it differs. It is saved as a draft: nothing is recorded on the orders until you confirm it.",
    chooseCourier: "Which courier paid you?",
    feePerOrder: "Fee per order",
    applyFee: "Apply to selected",
    selectAll: "Select all",
    selectOrder: "Select order {number}",
    selectedCount_one: "1 selected",
    selectedCount_other: "{n} selected",
    due: "Due",
    waybill: "Waybill",
    partOfOrder: "Part of order",
    delivered: "Delivered",
    collected: "Collected",
    courierFee: "Courier fee",
    totalsLine: "{count} · collected {collected} · fees {fees}",
    createDraft: "Create draft settlement",
    creating: "Saving…",
    draftCreated: "Draft settlement saved",
    invalidAmount: "Type the amount in digits only.",
    exceedsDue: "More than what's due on this order ({due}).",
    invalidFee: "Type the fee in digits only, or leave it empty.",

    errNotSettleable: "One of the orders can't be settled anymore — refresh and try again.",
    errDuplicate: "An order is on this settlement twice.",
    errExceeds: "A collected amount is more than what's due on its order.",
    errConfirmed: "This settlement is already confirmed and can't be changed.",
    errEmpty: "This settlement has no orders.",
  },
  ar: {
    title: "تسويات شركات الشحن",
    description: "طابق المبالغ التي حصّلتها شركات الشحن من الطلبات المسلَّمة مع ما حوّلته إليك فعلًا.",
    answerDue: "ما زال لدى شركات الشحن {amount} عن {orders} مسلَّمة.",
    answerClear: "لا توجد مبالغ متأخرة لدى شركات الشحن الآن.",
    record: "تسجيل تحويل",
    tools: "أدوات التسوية",
    importStatement: "استيراد كشف شركة الشحن",
    importHint: "طابق ملف CSV من شركة الشحن مع طلباتك",
    refresh: "تحديث",
    refreshHint: "إعادة جلب ما لدى شركات الشحن والتسويات",

    kpiDue: "لدى شركات الشحن",
    kpiDueHint: "عن {orders} مسلَّمة ولم تُسوَّ بعد",
    kpiDueNone: "لا شيء في الانتظار",
    kpiReceived: "ما وصلك",
    kpiReceivedHint: "صافي التسويات المؤكدة",
    kpiFees: "رسوم الشحن",
    kpiFeesHint: "خُصمت في التسويات المؤكدة",
    kpiDrafts: "تسويات مسودة",
    kpiDraftsHint: "تنتظر تأكيدك",
    kpiDraftsNone: "لا توجد مسودة في الانتظار",

    viewLabel: "ما تعرضه الصفحة",
    viewHeld: "لدى شركات الشحن",
    viewSettlements: "التسويات",

    heldLabel: "المبالغ لدى كل شركة شحن",
    colCourier: "شركة الشحن",
    daysBand: "{from}–{to} يومًا",
    daysOver: "أكثر من {n} يومًا",
    colTotal: "الإجمالي",
    colAction: "الخطوة التالية",
    ordersOldest: "{orders} · أقدم تسليم {date}",
    lateChip: "{amount} مضى عليها {n} يومًا",
    onTime: "لا شيء مضى عليه {n} يومًا",
    inDraft: "في مسودة تنتظر تأكيدك",
    recordFor: "تسجيل ما دفعته {courier}",
    noUnsettled: "لا توجد طلبات دفع عند الاستلام تحتاج إلى تسوية",
    noUnsettledDesc: "تبقى الطلبات المسلَّمة هنا إلى أن تحوّل شركة الشحن مبالغها إليك.",
    seeOrders: "عرض الطلبات",

    chipsLabel: "التسويات حسب الحالة",
    chipAll: "الكل",
    chipDraft: "مسودات",
    chipConfirmed: "مؤكدة",
    status_draft: "مسودة",
    status_confirmed: "مؤكدة",
    colDate: "أُنشئت",
    colStatus: "الحالة",
    colCollected: "المحصَّل",
    colFees: "الرسوم",
    colNet: "الصافي",
    confirmShort: "تأكيد",
    peek: "فتح تسوية {courier}، {date}",
    menuLabel: "إجراءات التسوية",
    menuOpen: "فتح التسوية",
    menuCopyRef: "نسخ المرجع",
    copiedRef: "تم نسخ المرجع",
    noSettlements: "لا توجد تسويات بعد",
    noSettlementsDesc: "التسوية تسجّل ما حوّلته إليك شركة الشحن عن الطلبات التي سلّمتها.",
    noDrafts: "لا توجد مسودة تنتظر التأكيد",
    noConfirmed: "لم تُؤكَّد أي تسوية بعد",
    showAll: "عرض كل التسويات",

    detailTitle: "تسوية · {carrier}",
    reference: "المرجع",
    period: "الفترة",
    periodRange: "{from} – {to}",
    createdOn: "أُنشئت",
    confirmedOn: "أُكّدت",
    notes: "ملاحظات",
    linesTitle: "الطلبات التي تتضمنها",
    lineOf: "من",
    orderGone: "طلب محذوف",
    openOrder: "فتح الطلب {number}",
    confirm: "تأكيد التسوية",
    delete: "حذف المسودة",
    confirmTitle: "تأكيد هذه التسوية؟",
    confirmDesc: "سيُسجَّل المبلغ المحصَّل دفعةً على كل طلب فيها وتُعلَّم الطلبات مدفوعة. التسوية المؤكدة لا يمكن تعديلها أو حذفها.",
    confirmed: "تم تأكيد التسوية",
    deleteTitle: "حذف هذه المسودة؟",
    deleteDesc: "تعود الطلبات إلى قائمة ما لم يُسوَّ بعد ولا يُسجَّل عليها شيء.",
    deleted: "تم حذف المسودة",

    reconcileTitle: "تسجيل تحويل",
    reconcileTitleFor: "ما دفعته {courier}",
    reconcileDesc: "حدّد الطلبات التي دفعت شركة الشحن قيمتها وعدّل المبلغ إن اختلف. تُحفظ مسودةً: لا يُسجَّل شيء على الطلبات حتى تؤكدها.",
    chooseCourier: "أي شركة شحن دفعت لك؟",
    feePerOrder: "الرسوم لكل طلب",
    applyFee: "تطبيق على المحدد",
    selectAll: "تحديد الكل",
    selectOrder: "تحديد الطلب {number}",
    selectedCount_one: "واحد محدد",
    selectedCount_two: "اثنان محددان",
    selectedCount_few: "{n} محددة",
    selectedCount_other: "{n} محددًا",
    due: "المستحق",
    waybill: "بوليصة",
    partOfOrder: "جزء من الطلب",
    delivered: "سُلّم",
    collected: "المحصَّل",
    courierFee: "رسوم الشحن",
    totalsLine: "{count} · محصَّل {collected} · رسوم {fees}",
    createDraft: "حفظ مسودة تسوية",
    creating: "جارٍ الحفظ…",
    draftCreated: "تم حفظ مسودة التسوية",
    invalidAmount: "اكتب المبلغ بالأرقام فقط.",
    exceedsDue: "أكثر من المستحق على هذا الطلب ({due}).",
    invalidFee: "اكتب الرسوم بالأرقام فقط، أو اترك الحقل فارغًا.",

    errNotSettleable: "أحد الطلبات لم يعد قابلًا للتسوية — حدّث وحاول مرة أخرى.",
    errDuplicate: "يوجد طلب مكرر في هذه التسوية.",
    errExceeds: "يوجد مبلغ محصَّل أكبر من المستحق على طلبه.",
    errConfirmed: "هذه التسوية مؤكدة ولا يمكن تغييرها.",
    errEmpty: "هذه التسوية لا تتضمن طلبات.",
  },
} satisfies Messages;

export type SettlementStrings = (typeof SETTLEMENT_STRINGS)["en"];

/** How late a courier may be before the page says so. */
export const LATE_DAYS = 14;

/** A refusal of the settlements API in the merchant's words; anything else as the dashboard words it. */
export function settlementErrorText(err: unknown, t: SettlementStrings): string {
  if (err instanceof ApiError) {
    if (err.code === "ORDER_NOT_SETTLEABLE") return t.errNotSettleable;
    if (err.code === "DUPLICATE_ORDER") return t.errDuplicate;
    if (err.code === "COLLECTED_EXCEEDS_DUE") return t.errExceeds;
    if (err.code === "SETTLEMENT_CONFIRMED") return t.errConfirmed;
    if (err.code === "SETTLEMENT_EMPTY") return t.errEmpty;
  }
  return getErrorMessage(err);
}
