import type { Messages } from "@/i18n/LocaleContext";

/**
 * Every word of the Rules tab, in one place: the tab, its rows and its
 * summaries all read from it through `useT(RULES_STRINGS)`.
 */
export const RULES_STRINGS = {
  en: {
    readOnlyTitle: "View only",
    readOnly: "Only the store owner or a workspace manager can change these rules.",
    readOnlyForbidden: "Your role can't change these rules, so they're shown read-only. Ask the store owner if they need changing.",
    orderRules: "Order rules",
    orderRulesHint: "Each rule is off until you switch it on, and each one has its own action.",
    visitorRules: "Where the order comes from",
    visitorRulesHint: "Checked against the shopper's internet address when they order.",
    customerRules: "The customer's history",
    customerRulesHint: "What this customer did before, here and across the platform.",
    then: "Then",
    action_flag: "Flag it for review",
    action_block: "Refuse the order",
    action_require_otp: "Ask for a code first",
    action_to_lost: "Move it to lost orders",
    duplicate_window_minutes: "Duplicate orders",
    duplicate_window_minutesHint: "The same customer orders any of the same products again within this many minutes.",
    duplicate_window_minutesUnit: "minutes",
    max_orders_per_phone_per_day: "Too many orders from one phone",
    max_orders_per_phone_per_dayHint: "The customer already placed this many orders in the last 24 hours.",
    max_orders_per_phone_per_dayUnit: "orders",
    high_rejection_threshold: "Customers who often refuse orders",
    high_rejection_thresholdHint: "The customer has rejected at least this many orders before.",
    high_rejection_thresholdUnit: "rejected orders",
    max_items_per_order: "Too many pieces of one product",
    max_items_per_orderHint: "The order holds more than this many units of the same product.",
    max_items_per_orderUnit: "pieces",
    min_minutes_between_cod_orders_per_ip: "Cash-on-delivery orders too close together",
    min_minutes_between_cod_orders_per_ipHint: "Another cash-on-delivery order came from the same internet address less than this many minutes ago.",
    min_minutes_between_cod_orders_per_ipUnit: "minutes",
    min_network_delivery_rate: "Low delivery rate",
    min_network_delivery_rateHint: "The customer's delivery rate across all stores is below this percentage.",
    min_network_delivery_rateUnit: "%",
    block_outside_country: "Orders from other countries",
    block_outside_countryHint: "The shopper is not in one of the allowed countries.",
    block_vpn: "VPN and server addresses",
    block_vpnHint: "The shopper is hiding behind a VPN or ordering from a data centre.",
    high_risk: "High-risk orders",
    high_riskHint: "The order's risk level came out as high.",
    allowedCountries: "Allowed countries",
    allowedCountriesHint: "Two-letter country codes separated by commas, for example EG, SA. Leave empty for your store's country only.",
    allowedCountriesError: "Use two-letter country codes separated by commas.",
    rangeError: "Enter a whole number from {min} to {max}.",
    otpHeading: "Phone verification",
    otpEnabled: "Ask for a code before the order is placed",
    otpEnabledHint: "The shopper gets a code and types it in. No order, stock hold or pixel event exists until the number is verified; unverified attempts go to lost orders.",
    otpChannel: "Send the code by",
    otpChannel_whatsapp: "WhatsApp (SMS if it cannot be sent)",
    otpChannel_sms: "SMS",
    otpApply: "Ask",
    otpApply_all: "Every order",
    otpApply_cod_only: "Cash-on-delivery orders only",
    otpApply_risky_only: "Risky orders only",
    otpLength: "Code length",
    otpDigits: "{n} digits",
    botCaptcha: "Add an invisible challenge",
    botCaptchaHint: "A background check the shopper never sees (Cloudflare Turnstile). It only acts once the challenge provider is connected to the platform.",
    visitorsHeading: "Visitors",
    botProtection: "Bot protection",
    botProtectionHint: "Refuses orders sent by scripts: a hidden field only a bot fills, and a check that the form was open for at least three seconds. Refused attempts go to lost orders.",
    blockedCountries: "Countries that cannot see the store",
    blockedCountriesHint: "Two-letter country codes separated by commas. Visitors from these countries see the store as unavailable. Block single addresses in the Blocked tab.",
    alwaysHeading: "Always",
    strictPhone: "Only accept real mobile numbers",
    strictPhoneHint: "A number that is not a mobile number of your store's country is refused, and the shopper is asked to correct it.",
    blockBlacklisted: "Always refuse blocked customers",
    blockBlacklistedHint: "When off, orders matching the blocked list are still placed but flagged. Manage the list in the Blocked tab.",
    save: "Save rules",
    saving: "Saving…",
    reset: "Discard changes",
    saved: "Rules saved.",
    // What a folded section says about itself.
    rulesOn_one: "1 rule on",
    rulesOn_other: "{n} rules on",
    rulesOff: "No rule is on",
    chipCount: "{on} of {total}",
    chipOn: "On",
    chipOff: "Off",
    chipCheck: "Check",
    summarySep: " · ",
    otpOffSummary: "Code verification is off",
    otpBy_whatsapp: "Code by WhatsApp",
    otpBy_sms: "Code by SMS",
    botOnSummary: "Bot protection is on",
    botOffSummary: "Bot protection is off",
    botCaptchaSummary: "invisible challenge",
    countriesHidden_one: "1 country hidden",
    countriesHidden_other: "{n} countries hidden",
    alwaysStrictSummary: "Real mobile numbers only",
    alwaysBlockSummary: "Blocked customers refused",
    alwaysNone: "Nothing here is on",
  },
  ar: {
    readOnlyTitle: "عرض فقط",
    readOnly: "يمكن لمالك المتجر أو مدير مساحة العمل فقط تغيير هذه القواعد.",
    readOnlyForbidden: "دورك لا يسمح بتغيير هذه القواعد، لذلك تظهر للعرض فقط. اطلب من مالك المتجر إذا احتاجت إلى تعديل.",
    orderRules: "قواعد الطلب",
    orderRulesHint: "كل قاعدة متوقفة حتى تفعّلها، ولكل قاعدة إجراء خاص بها.",
    visitorRules: "من أين يأتي الطلب",
    visitorRulesHint: "تُفحص على عنوان الإنترنت للمشتري وقت الطلب.",
    customerRules: "تاريخ العميل",
    customerRulesHint: "ما فعله هذا العميل من قبل، عندك وعلى مستوى المنصة.",
    then: "الإجراء",
    action_flag: "تمييزه للمراجعة",
    action_block: "رفض الطلب",
    action_require_otp: "طلب كود تحقق أولًا",
    action_to_lost: "تحويله إلى الطلبات المفقودة",
    duplicate_window_minutes: "الطلبات المكررة",
    duplicate_window_minutesHint: "يطلب العميل نفسه أيًّا من نفس المنتجات مرة أخرى خلال هذا العدد من الدقائق.",
    duplicate_window_minutesUnit: "دقيقة",
    max_orders_per_phone_per_day: "طلبات كثيرة من نفس الهاتف",
    max_orders_per_phone_per_dayHint: "سجّل العميل هذا العدد من الطلبات خلال آخر 24 ساعة.",
    max_orders_per_phone_per_dayUnit: "طلب",
    high_rejection_threshold: "عملاء يرفضون الطلبات كثيرًا",
    high_rejection_thresholdHint: "رفض العميل هذا العدد من الطلبات على الأقل من قبل.",
    high_rejection_thresholdUnit: "طلب مرفوض",
    max_items_per_order: "قطع كثيرة من نفس المنتج",
    max_items_per_orderHint: "الطلب فيه أكثر من هذا العدد من القطع من نفس المنتج.",
    max_items_per_orderUnit: "قطعة",
    min_minutes_between_cod_orders_per_ip: "طلبات دفع عند الاستلام متقاربة",
    min_minutes_between_cod_orders_per_ipHint: "جاء طلب دفع عند الاستلام آخر من نفس عنوان الإنترنت منذ أقل من هذا العدد من الدقائق.",
    min_minutes_between_cod_orders_per_ipUnit: "دقيقة",
    min_network_delivery_rate: "نسبة استلام منخفضة",
    min_network_delivery_rateHint: "نسبة استلام العميل على مستوى كل المتاجر أقل من هذه النسبة.",
    min_network_delivery_rateUnit: "٪",
    block_outside_country: "طلبات من دول أخرى",
    block_outside_countryHint: "المشتري ليس في إحدى الدول المسموح بها.",
    block_vpn: "عناوين VPN والسيرفرات",
    block_vpnHint: "المشتري يتخفى وراء VPN أو يطلب من مركز بيانات.",
    high_risk: "الطلبات عالية الخطورة",
    high_riskHint: "مستوى خطورة الطلب «عالٍ».",
    allowedCountries: "الدول المسموح بها",
    allowedCountriesHint: "أكواد الدول من حرفين مفصولة بفواصل، مثل EG, SA. اتركها فارغة لدولة متجرك فقط.",
    allowedCountriesError: "استخدم أكواد دول من حرفين مفصولة بفواصل.",
    rangeError: "أدخل رقمًا صحيحًا من {min} إلى {max}.",
    otpHeading: "تأكيد رقم الهاتف",
    otpEnabled: "طلب كود تحقق قبل تسجيل الطلب",
    otpEnabledHint: "يوصل للمشتري كود ويكتبه. لا يُسجَّل طلب ولا يُحجز مخزون ولا يُرسَل حدث بيكسل قبل تأكيد الرقم؛ المحاولات غير المؤكدة تذهب إلى الطلبات المفقودة.",
    otpChannel: "إرسال الكود عبر",
    otpChannel_whatsapp: "واتساب (ورسالة SMS إذا تعذّر)",
    otpChannel_sms: "رسالة SMS",
    otpApply: "يُطلب من",
    otpApply_all: "كل الطلبات",
    otpApply_cod_only: "طلبات الدفع عند الاستلام فقط",
    otpApply_risky_only: "الطلبات الخطرة فقط",
    otpLength: "طول الكود",
    otpDigits: "{n} أرقام",
    botCaptcha: "إضافة تحدٍّ غير مرئي",
    botCaptchaHint: "فحص في الخلفية لا يراه المشتري (Cloudflare Turnstile). لا يعمل إلا بعد ربط مزوّد التحدي بالمنصة.",
    visitorsHeading: "الزوار",
    botProtection: "الحماية من البوتات",
    botProtectionHint: "ترفض الطلبات المرسلة بسكربتات: حقل مخفي لا يملؤه إلا البوت، والتأكد أن النموذج كان مفتوحًا ثلاث ثوانٍ على الأقل. المحاولات المرفوضة تذهب إلى الطلبات المفقودة.",
    blockedCountries: "دول لا ترى المتجر",
    blockedCountriesHint: "أكواد دول من حرفين تفصل بينها فاصلة. يظهر للزوار من هذه الدول أن المتجر غير متاح. العناوين المفردة احجبها من تبويب «المحظورون».",
    alwaysHeading: "دائمًا",
    strictPhone: "قبول أرقام الهاتف الحقيقية فقط",
    strictPhoneHint: "الرقم الذي ليس رقم هاتف في دولة متجرك يُرفض، ويُطلب من المشتري تصحيحه.",
    blockBlacklisted: "رفض العملاء المحظورين دائمًا",
    blockBlacklistedHint: "إذا كانت مغلقة، تُسجَّل الطلبات المطابقة لقائمة المحظورين لكنها تُعلَّم. القائمة في تبويب «المحظورون».",
    save: "حفظ القواعد",
    saving: "جارٍ الحفظ…",
    reset: "تجاهل التغييرات",
    saved: "تم حفظ القواعد.",
    rulesOn_one: "قاعدة واحدة شغّالة",
    rulesOn_two: "قاعدتين شغّالين",
    rulesOn_few: "{n} قواعد شغّالة",
    rulesOn_other: "{n} قاعدة شغّالة",
    rulesOff: "لا توجد قاعدة مفعّلة",
    chipCount: "{on} من {total}",
    chipOn: "مفعّل",
    chipOff: "متوقف",
    chipCheck: "راجع",
    summarySep: " · ",
    otpOffSummary: "التأكيد بالكود متوقف",
    otpBy_whatsapp: "كود على واتساب",
    otpBy_sms: "كود برسالة SMS",
    botOnSummary: "حماية البوتات شغّالة",
    botOffSummary: "حماية البوتات متوقفة",
    botCaptchaSummary: "تحدّي مخفي",
    countriesHidden_one: "بلد واحدة محجوبة",
    countriesHidden_two: "بلدين محجوبين",
    countriesHidden_few: "{n} بلاد محجوبة",
    countriesHidden_other: "{n} بلد محجوبة",
    alwaysStrictSummary: "أرقام هاتف حقيقية فقط",
    alwaysBlockSummary: "المحظورون يُرفضون",
    alwaysNone: "لا شيء مفعّل هنا",
  },
} satisfies Messages;

export type RulesStrings = Record<keyof typeof RULES_STRINGS.en, string>;
