/**
 * The icons of the screens ported from zimos-additions, named by what each
 * glyph means here. Every one is a lucide-react icon, like the rest of the
 * dashboard; those screens import from this file, so a glyph is changed in
 * one place.
 *
 * Decorative icons are `aria-hidden`; an icon-only button has an `aria-label`
 * through `useT`. Arrows, carets and "back" flip in RTL (`rtl:rotate-180` /
 * `rtl:-scale-x-100`); a phone, a clock or a chart does not.
 */
import type { LucideIcon, LucideProps } from "lucide-react";

export type Icon = LucideIcon;
/** The same type under a name that never collides with a local `Icon` variable. */
export type IconComponent = LucideIcon;
export type IconProps = LucideProps;

export {
  CircleUser as IconAccount,
  Megaphone as IconAnnounce,
  ArrowDown as IconArrowDown,
  ArrowLeft as IconArrowLeft,
  ArrowUpRight as IconArrowOut,
  ArrowUp as IconArrowUp,
  Medal as IconAward,
  Bell as IconBell,
  Ban as IconBlock,
  Newspaper as IconBlog,
  Layers as IconBoxes,
  Calendar as IconCalendar,
  CreditCard as IconCard,
  ChevronDown as IconCaretDown,
  ChevronLeft as IconCaretLeft,
  ChevronRight as IconCaretRight,
  ChevronUp as IconCaretUp,
  ChevronsUpDown as IconCaretUpDown,
  Banknote as IconCash,
  ChartColumn as IconChart,
  MessageCircle as IconChat,
  Check as IconCheck,
  ListChecks as IconChecklist,
  MousePointerClick as IconClick,
  Clock as IconClock,
  X as IconClose,
  Coins as IconCoins,
  Contrast as IconContrast,
  Copy as IconCopy,
  Truck as IconCourier,
  Crown as IconCrown,
  Users as IconCustomers,
  Trash2 as IconDelete,
  Monitor as IconDesktop,
  MonitorSmartphone as IconDevices,
  Tag as IconDiscounts,
  SeparatorHorizontal as IconDivider,
  Download as IconDownload,
  PencilRuler as IconDraft,
  Pencil as IconEdit,
  Mail as IconEmail,
  CornerDownLeft as IconEnter,
  ExternalLink as IconExternal,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  FileQuestionMark as IconFileUnknown,
  FileUp as IconFileUp,
  ListFilter as IconFilter,
  Folder as IconFolder,
  Route as IconFunnels,
  Gift as IconGift,
  Ticket as IconGiftCards,
  Heading as IconHeading,
  Heart as IconHeart,
  TreePalm as IconHoliday,
  House as IconHome,
  Hourglass as IconHourglass,
  Image as IconImage,
  ImageOff as IconImageMissing,
  Info as IconInfo,
  KeyRound as IconKey,
  Keyboard as IconKeyboard,
  Rocket as IconLaunch,
  Link as IconLink,
  List as IconListView,
  Lock as IconLock,
  Images as IconMedia,
  MessageSquareText as IconMessage,
  Minus as IconMinus,
  Moon as IconMoon,
  List as IconMore,
  Ellipsis as IconMoreActions,
  FileSpreadsheet as IconMoreReports,
  NotebookPen as IconNote,
  Gift as IconOffers,
  ShoppingBag as IconOrders,
  Package as IconPackage,
  Package as IconPackageSearch,
  AppWindow as IconPage,
  Pilcrow as IconParagraph,
  Pause as IconPause,
  Users as IconPeople,
  Percent as IconPercent,
  Phone as IconPhone,
  Smartphone as IconPhoneDevice,
  Pin as IconPin,
  MapPin as IconPlace,
  Play as IconPlay,
  Plus as IconPlus,
  Power as IconPower,
  Box as IconProduct,
  Package as IconProducts,
  CircleQuestionMark as IconQuestions,
  ZoomIn as IconQuickLook,
  Quote as IconQuote,
  Activity as IconRealtime,
  Receipt as IconReceipt,
  RefreshCw as IconRefresh,
  Undo2 as IconReturns,
  RotateCcw as IconRotateBack,
  Ruler as IconRuler,
  Scale as IconScale,
  CalendarDays as IconSchedule,
  Search as IconSearch,
  Send as IconSend,
  Settings as IconSettings,
  Share2 as IconShare,
  ShieldCheck as IconShield,
  Shuffle as IconShuffle,
  PanelLeft as IconSidebar,
  LogOut as IconSignOut,
  SlidersHorizontal as IconSliders,
  LoaderCircle as IconSpinner,
  Store as IconStore,
  CircleCheck as IconSuccess,
  Sun as IconSun,
  Table as IconTable,
  Users as IconTeam,
  Palette as IconTheme,
  Ticket as IconTicket,
  Lightbulb as IconTip,
  Network as IconTree,
  TrendingDown as IconTrendDown,
  TrendingUp as IconTrendUp,
  Undo2 as IconUndo,
  PinOff as IconUnpin,
  Upload as IconUpload,
  User as IconUser,
  UserPlus as IconUserAdd,
  Video as IconVideo,
  Wallet as IconWallet,
  TriangleAlert as IconWarning,
  MessageCircle as IconWhatsApp,
} from "lucide-react";
