import type { Messages } from "@/i18n/LocaleContext";

/** Every string of the funnel's settings sheet (FunnelGrowthPanel.tsx and its parts in this folder). */
export const SHEET_STRINGS = {
  en: {
    // shell
    open: "Funnel settings",
    title: "Funnel settings",
    parts: "Part of the settings",
    tabSettings: "Settings",
    tabTests: "A/B tests",
    tabTestsShort: "A/B",
    tabGeo: "Countries",
    savesAlone: "These settings save on their own — not with the funnel's Save.",
    unsavedTitle: "You have changes that are not saved",
    unsavedBody: "If you go on, what you changed here is lost.",
    unsavedStay: "Keep editing",
    unsavedLeave: "Leave them",
    cancel: "Cancel",
    discard: "Discard",
    close: "Close",
    retry: "Try again",

    // settings
    settingsUnsaved: "Settings not saved yet",
    save: "Save settings",
    saving: "Saving…",
    saved: "Settings saved.",
    currency: "Funnel currency (3 letters)",
    currencyHint: "What this funnel sells in; its offers must be priced in it. Empty = the store's.",
    searchFold: "How the funnel shows in search",
    searchFoldSummary: "Title, description and icon — empty = the store's",
    seoTitle: "Search title",
    seoDescription: "Search description",
    favicon: "Icon link",
    advancedFold: "Advanced",
    advancedSummary: "Your own code on every step",
    advancedSummaryOn: "There is code on this funnel's pages",

    // tests — list
    testsIntro: "Show one step in two or more versions and keep the one that sells more. A is the page as it is now; each other version starts as a copy you then change.",
    noTests: "No test on this funnel yet",
    noTestsDesc: "Try another headline or another price on one step and let the visitors decide.",
    noSteps: "Add a step to the funnel first, then test it.",
    newTest: "New test",
    onStep: "On step: {page}",
    running: "Running",
    paused: "Paused",
    completed: "Finished",
    openTest: "Open the test «{name}»",
    visits: "Visits",
    orders: "Orders",
    rate: "Conversion",
    revenue: "Revenue",
    epc: "Per visit",
    share: "Share",
    numbersLoading: "Loading the numbers…",
    numbersFailed: "Couldn't load this test's numbers.",
    winner: "Winner",
    leader: "Ahead",
    early: "Too early — not enough visits yet to tell the versions apart.",
    closeCall: "The versions are close: no clear difference yet.",
    leaderLine: "{leader} is ahead — {pct}% sure it really converts better.",
    leaderVsLine: "{leader} is ahead — {pct}% sure it really converts better than {runnerUp}.",
    winnerLine: "{winner} won: every visitor sees its page now.",
    control: "A — original",

    // tests — create
    backToTests: "Tests",
    createTitle: "New test",
    page: "Step to test",
    stepHasTest: "{name} — already has a test",
    name: "Test name",
    namePlaceholder: "Headline test",
    auto: "Pick the winner automatically",
    autoHint: "The test ends by itself once it has enough visits.",
    afterVisits: "After this many visits",
    metric: "By",
    conversion_rate: "Conversion rate",
    revenue_per_visit: "Revenue per visit",
    create: "Start test",
    creating: "Starting…",
    created: "The test is running.",
    needsSaved: "Save the funnel first: this step has not been saved yet.",
    createUnsaved: "The test has not started yet",

    // tests — detail
    autoLine: "It picks the winner by itself after {n} visits, by {metric}.",
    pause: "Pause the test",
    resume: "Resume the test",
    pausedToast: "Test paused. Visitors see the original page.",
    resumedToast: "The test is running again.",
    makeWinner: "Make it the winner",
    winnerTitle: "Make {version} the winner?",
    winnerBody: "The test ends and every visitor sees {version}'s page. A finished test cannot be started again.",
    winnerConfirm: "End the test",
    winnerToast: "{version} won. The test is finished.",
    remove: "Delete test",
    removeTitle: "Delete the test «{name}»?",
    removeBody: "Its numbers are deleted for good and visitors go back to the step's own page.",
    removeConfirm: "Delete",
    removedToast: "Test deleted.",
    doneNote: "The funnel's own page did not change: visitors see {winner}'s page while this test exists. Delete the test and the original page shows again.",
    editPage: "Edit {key}'s page",
    versionsFold: "Versions and shares",
    versionsFoldSummary: "Add a version or move the shares",
    saveVersions: "Save versions and shares",
    versionsUnsaved: "Shares not saved yet",
    savedVersions: "Saved. New visitors are shared out the new way; visitors already in a version stay in it.",

    // tests — a version's page
    backToTest: "The test",
    pageTitle: "Version {key}'s page",
    savePage: "Save {key}'s page",
    savedPage: "{key}'s page saved. It is live for visitors in {key} at once.",
    stepGone: "This step is no longer in the funnel, so its versions cannot be edited.",

    // geo
    geoIntro: "Send visitors from some countries to another funnel — for another language, currency or shipping. Everyone else sees this one.",
    noRules: "No country redirect on this funnel",
    noRulesDesc: "Everyone sees this funnel, wherever they are.",
    ruleTo: "go to",
    active: "On",
    ruleActive: "Redirect for {countries} is on",
    removeRule: "Delete the redirect for {countries}",
    ruleRemoved: "Redirect deleted.",
    addTitle: "New redirect",
    quickPick: "Tap to pick",
    countries: "Other countries (2-letter codes, comma-separated)",
    countriesPlaceholder: "SA, AE, KW",
    target: "Send them to",
    chooseFunnel: "Choose a funnel",
    onlyPublished: "The redirect applies while the target funnel is published.",
    addRule: "Add redirect",
    adding: "Adding…",
    ruleAdded: "Redirect added.",
    geoUnsaved: "A redirect not added yet",
  },
  ar: {
    open: "إعدادات مسار البيع",
    title: "إعدادات مسار البيع",
    parts: "أقسام الإعدادات",
    tabSettings: "الإعدادات",
    tabTests: "اختبارات A/B",
    tabTestsShort: "A/B",
    tabGeo: "الدول",
    savesAlone: "هذه الإعدادات تُحفظ وحدها — لا مع حفظ مسار البيع.",
    unsavedTitle: "لديك تغييرات لم تُحفظ بعد",
    unsavedBody: "إذا تابعت، ستفقد ما غيّرته هنا.",
    unsavedStay: "متابعة التعديل",
    unsavedLeave: "تركها",
    cancel: "إلغاء",
    discard: "تجاهل",
    close: "إغلاق",
    retry: "إعادة المحاولة",

    settingsUnsaved: "إعدادات لم تُحفظ بعد",
    save: "حفظ الإعدادات",
    saving: "جارٍ الحفظ…",
    saved: "تم حفظ الإعدادات.",
    currency: "عملة مسار البيع (٣ حروف)",
    currencyHint: "العملة التي يبيع بها مسار البيع؛ يجب أن تكون عروضه مسعّرة بها. إذا تركتها فارغة فهي عملة المتجر.",
    searchFold: "ظهور مسار البيع في البحث",
    searchFoldSummary: "العنوان والوصف والأيقونة — إن تُركت فارغة استُخدمت بيانات المتجر",
    seoTitle: "عنوان البحث",
    seoDescription: "وصف البحث",
    favicon: "رابط الأيقونة",
    advancedFold: "متقدّم",
    advancedSummary: "كود خاص بك على كل الخطوات",
    advancedSummaryOn: "يوجد كود على صفحات هذا المسار",

    testsIntro: "اعرض خطوة واحدة بنسختين أو أكثر وأبقِ الأكثر بيعًا. A هي الصفحة كما هي الآن؛ وكل نسخة أخرى تبدأ نسخةً منها ثم تعدّلها.",
    noTests: "لا يوجد اختبار على هذا المسار بعد",
    noTestsDesc: "جرّب عنوانًا آخر أو سعرًا آخر على خطوة واحدة، ودع الزوار يحكمون.",
    noSteps: "أضف خطوة إلى مسار البيع أولًا، ثم اختبرها.",
    newTest: "اختبار جديد",
    onStep: "على خطوة: {page}",
    running: "يعمل",
    paused: "متوقف",
    completed: "انتهى",
    openTest: "فتح الاختبار «{name}»",
    visits: "الزيارات",
    orders: "الطلبات",
    rate: "التحويل",
    revenue: "الإيرادات",
    epc: "لكل زيارة",
    share: "النسبة",
    numbersLoading: "جارٍ تحميل الأرقام…",
    numbersFailed: "تعذّر تحميل أرقام هذا الاختبار.",
    winner: "الفائزة",
    leader: "متقدّمة",
    early: "ما زال الوقت مبكرًا — الزيارات قليلة ولا تكفي للتفريق بين النسخ.",
    closeCall: "النسخ متقاربة: لا يوجد فرق واضح بعد.",
    leaderLine: "{leader} متقدّمة — نسبة الثقة {pct}% في أنها تحوّل أفضل فعلًا.",
    leaderVsLine: "{leader} متقدّمة — نسبة الثقة {pct}% في أنها تحوّل أفضل من {runnerUp} فعلًا.",
    winnerLine: "{winner} فازت: يرى كل الزوار صفحتها الآن.",
    control: "A — الأصلية",

    backToTests: "الاختبارات",
    createTitle: "اختبار جديد",
    page: "الخطوة التي ستختبرها",
    stepHasTest: "{name} — عليها اختبار",
    name: "اسم الاختبار",
    namePlaceholder: "اختبار العنوان",
    auto: "اختيار الفائزة تلقائيًا",
    autoHint: "ينتهي الاختبار تلقائيًا فور اكتمال عدد الزيارات.",
    afterVisits: "بعد كم زيارة",
    metric: "حسب",
    conversion_rate: "نسبة التحويل",
    revenue_per_visit: "الإيراد لكل زيارة",
    create: "بدء الاختبار",
    creating: "جارٍ البدء…",
    created: "الاختبار يعمل.",
    needsSaved: "احفظ مسار البيع أولًا: هذه الخطوة لم تُحفظ بعد.",
    createUnsaved: "الاختبار لم يبدأ بعد",

    autoLine: "سيختار الفائزة تلقائيًا بعد {n} زيارة، حسب {metric}.",
    pause: "إيقاف الاختبار مؤقتًا",
    resume: "تشغيل الاختبار مجددًا",
    pausedToast: "توقف الاختبار. يرى الزوار الصفحة الأصلية.",
    resumedToast: "عاد الاختبار إلى العمل.",
    makeWinner: "اجعلها الفائزة",
    winnerTitle: "هل تجعل {version} هي الفائزة؟",
    winnerBody: "سينتهي الاختبار ويرى كل الزوار صفحة {version}. الاختبار المنتهي لا يُعاد تشغيله.",
    winnerConfirm: "إنهاء الاختبار",
    winnerToast: "{version} فازت. انتهى الاختبار.",
    remove: "حذف الاختبار",
    removeTitle: "هل تحذف الاختبار «{name}»؟",
    removeBody: "ستُحذف أرقامه نهائيًا، ويعود الزوار إلى رؤية صفحة الخطوة نفسها.",
    removeConfirm: "حذف",
    removedToast: "تم حذف الاختبار.",
    doneNote: "صفحة مسار البيع نفسها لم تتغيّر: يرى الزوار صفحة {winner} ما دام الاختبار موجودًا. إذا حذفته، عادت الصفحة الأصلية إلى الظهور.",
    editPage: "تعديل صفحة {key}",
    versionsFold: "النسخ والنسب",
    versionsFoldSummary: "أضف نسخة أو غيّر النسب",
    saveVersions: "حفظ النسخ والنسب",
    versionsUnsaved: "نسب لم تُحفظ بعد",
    savedVersions: "تم الحفظ. يتوزّع الزوار الجدد بالنسب الجديدة، ومن دخل نسخة يبقى فيها.",

    backToTest: "الاختبار",
    pageTitle: "صفحة النسخة {key}",
    savePage: "حفظ صفحة {key}",
    savedPage: "تم حفظ صفحة {key}. تظهر فورًا للزوار الموجودين في {key}.",
    stepGone: "هذه الخطوة لم تعد في مسار البيع، فلا يمكن تعديل نسخها.",

    geoIntro: "وجّه زوار دول معيّنة إلى مسار بيع آخر — للغة أو عملة أو شحن مختلف. والباقون يرون هذا المسار.",
    noRules: "لا يوجد تحويل حسب الدولة على هذا المسار",
    noRulesDesc: "يرى الجميع هذا المسار، من أي بلد.",
    ruleTo: "ينتقلون إلى",
    active: "مفعّل",
    ruleActive: "تحويل {countries} مفعّل",
    removeRule: "حذف تحويل {countries}",
    ruleRemoved: "تم حذف التحويل.",
    addTitle: "تحويل جديد",
    quickPick: "اضغط للاختيار",
    countries: "دول أخرى (رمز من حرفين، تفصل بينها فاصلة)",
    countriesPlaceholder: "SA, AE, KW",
    target: "وجّههم إلى",
    chooseFunnel: "اختر مسار بيع",
    onlyPublished: "يعمل التحويل ما دام مسار البيع الآخر منشورًا.",
    addRule: "إضافة التحويل",
    adding: "جارٍ الإضافة…",
    ruleAdded: "تمت إضافة التحويل.",
    geoUnsaved: "تحويل لم يُضف بعد",
  },
} satisfies Messages;
