import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the new-funnel wizard: three questions — what you sell, which
 * offer, which template — then "Build the funnel". Also the share-code dialog
 * and the "I have a code" screen. Second person, short.
 */
export const WIZARD_STRINGS = {
  en: {
    // Frame
    progress: "Question {n} of {total}",
    back: "Back",
    next: "Next",
    cancel: "Cancel",
    build: "Build the funnel",
    building: "Building…",
    // 1. Product
    q1: "What do you sell?",
    q1Hint: "The funnel's pages follow this product. You can change it later, page by page.",
    searchProducts: "Search your products",
    searchProductsPlaceholder: "Product name",
    products: "Your products",
    picked: "Chosen",
    change: "Change",
    noPrice: "No price yet",
    noProductsTitle: "No products yet",
    noProductsBody: "A funnel sells one product. Add it first, then come back here.",
    addProduct: "Add a product first",
    withoutProduct: "Continue without a product",
    withoutProductHint: "The pages will show the store's newest product until you choose one.",
    noProductPicked: "No product chosen",
    noMatch: "No product with that name.",
    productsFailed: "Couldn't load your products.",
    retry: "Try again",
    moreProducts: "Showing the first {n}. Type a name to find the rest.",
    haveCode: "I have a funnel code",
    onlyLeads: "I'm not selling — I collect customer numbers",
    // 2. Offer
    q2: "Which offer?",
    q2Hint: "What the order form sells with, and whether the shopper sees one more offer after ordering.",
    orderForm: "The order form",
    orderFormOffer: "Sells with the product's main offer: {offer}",
    orderFormPrice: "Sells at the product's price: {price}",
    orderFormPlain: "Sells at the product's price, with no offer.",
    orderFormNoProduct: "Sells the product each page shows.",
    productOffers: "The product's offers",
    mainOffer: "Main",
    manageOffers: "Edit the product's offers",
    upsell: "Offer after the order (upsell)",
    upsellHint: "Right after the order is placed, one more offer the shopper accepts in one tap. It adds an offer step to the funnel.",
    upsellWhich: "What will you offer?",
    upsellLater: "I'll choose it in the editor",
    upsellLaterHint: "The funnel can't be published until the offer step has an offer.",
    fromThisProduct: "From this product",
    otherOffers: "Other offers in the store",
    noOffers: "The store has no active offers yet. Build the funnel now and choose the offer in the editor once you add one.",
    offersFailed: "Couldn't load the offers. You can still choose one in the editor.",
    offerOf: "{offer} — {product}",
    // 3. Template
    q3: "Which look?",
    q3Hint: "A ready funnel to start from. Everything in it can be changed after.",
    q3LeadsHint: "A form that collects names and numbers, then a thank-you page.",
    name: "Funnel name",
    nameRequired: "Give the funnel a name.",
    moreDetails: "Link",
    link: "Link",
    linkHint: "Letters, numbers and hyphens. Leave it empty and one is made from the name.",
    linkInvalid: "Use 3 to 63 small letters, numbers and hyphens.",
    aiNeedsProduct: "The AI writes the page from a product. Go back and choose one.",
    chooseProduct: "Choose a product",
    summary: "You're building",
    summaryProduct: "Product: {name}",
    summaryNoProduct: "No product chosen yet",
    summaryUpsell: "With an offer after the order",
    summaryNoUpsell: "No offer after the order",
    summaryLeads: "Collects customer numbers",
    // Results
    created: "“{name}” is ready.",
    createdPartial: "The funnel was made, but not all of its pages came with it: {message}",
    productByHand: "The funnel is ready, but not everything was written ({message}). Check the product on its pages in the editor.",
    q1Missing: "Choose a product, or continue without one.",
    steps: "Wizard steps",
    offerByHand: "The funnel is ready, but the offer didn't reach the offer step. Choose it there in the editor.",
    planLimit: "Upgrade the plan",
    // By code
    codeTitle: "Copy a funnel by code",
    codeBody: "The code another merchant gave you. You get the funnel's pages and links, without their products or orders.",
    code: "Funnel code",
    importIt: "Copy the funnel",
    importing: "Copying…",
    imported: "“{name}” copied — {steps} pages. Choose your products before you publish.",
    // Share by code
    shareTitle: "Share this funnel by code",
    shareDescription: "Give this code to another merchant. They get a copy of the funnel's pages and links — not your products, offers or orders.",
    shareStop: "Stop sharing",
    shareStopped: "Sharing stopped. The old code no longer works.",
    shareCode: "Share by code",
    copy: "Copy the code",
    codeLoading: "Getting the code…",
    close: "Close",
  },
  ar: {
    progress: "السؤال {n} من {total}",
    back: "رجوع",
    next: "التالي",
    cancel: "إلغاء",
    build: "إنشاء مسار البيع",
    building: "جارٍ الإنشاء…",
    q1: "ماذا تبيع؟",
    q1Hint: "صفحات مسار البيع تتبع هذا المنتج. يمكنك تغييره لاحقًا لكل صفحة.",
    searchProducts: "ابحث في منتجاتك",
    searchProductsPlaceholder: "اسم المنتج",
    products: "منتجاتك",
    picked: "تم اختياره",
    change: "تغيير",
    noPrice: "بدون سعر بعد",
    noProductsTitle: "لا توجد منتجات بعد",
    noProductsBody: "مسار البيع يبيع منتجًا واحدًا. أضفه أولًا ثم عد إلى هنا.",
    addProduct: "أضف منتجًا أولًا",
    withoutProduct: "المتابعة بدون منتج",
    withoutProductHint: "ستعرض الصفحات أحدث منتج في المتجر إلى أن تختار منتجًا.",
    noProductPicked: "بدون منتج",
    noMatch: "لا يوجد منتج بهذا الاسم.",
    productsFailed: "تعذّر تحميل منتجاتك.",
    retry: "إعادة المحاولة",
    moreProducts: "هذه أول {n}. اكتب اسمًا للعثور على الباقي.",
    haveCode: "لديّ كود مسار بيع",
    onlyLeads: "لا أبيع — أجمع أرقام العملاء",
    q2: "أي عرض؟",
    q2Hint: "بماذا يبيع نموذج الطلب، وهل يرى العميل عرضًا آخر بعد أن يطلب.",
    orderForm: "نموذج الطلب",
    orderFormOffer: "يبيع بالعرض الأساسي للمنتج: {offer}",
    orderFormPrice: "يبيع بسعر المنتج: {price}",
    orderFormPlain: "يبيع بسعر المنتج، بدون عرض.",
    orderFormNoProduct: "يبيع المنتج الذي تعرضه كل صفحة.",
    productOffers: "عروض المنتج",
    mainOffer: "الأساسي",
    manageOffers: "تعديل عروض المنتج",
    upsell: "عرض بعد الشراء (upsell)",
    upsellHint: "فور إتمام الطلب، عرض آخر يقبله العميل بضغطة واحدة. يضيف خطوة عرض إلى مسار البيع.",
    upsellWhich: "ماذا ستعرض عليه؟",
    upsellLater: "سأختاره من المحرر",
    upsellLaterHint: "لا يُنشر مسار البيع حتى يكون لخطوة العرض عرض.",
    fromThisProduct: "من هذا المنتج",
    otherOffers: "عروض أخرى في المتجر",
    noOffers: "لا توجد عروض نشطة في المتجر بعد. أنشئ مسار البيع الآن واختر العرض من المحرر عندما تضيف عرضًا.",
    offersFailed: "تعذّر تحميل العروض. يمكنك اختيار العرض من المحرر.",
    offerOf: "{offer} — {product}",
    q3: "أي شكل؟",
    q3Hint: "مسار بيع جاهز تبدأ منه. كل ما فيه يمكن تغييره لاحقًا.",
    q3LeadsHint: "نموذج يجمع الأسماء والأرقام، ثم صفحة شكر.",
    name: "اسم مسار البيع",
    nameRequired: "اكتب اسمًا لمسار البيع.",
    moreDetails: "الرابط",
    link: "الرابط",
    linkHint: "حروف وأرقام وشرطات. اتركه فارغًا ليُصنع من الاسم.",
    linkInvalid: "استخدم من 3 إلى 63 حرفًا صغيرًا وأرقامًا وشرطات.",
    aiNeedsProduct: "الذكاء الاصطناعي يكتب الصفحة من منتج. ارجع واختر منتجًا.",
    chooseProduct: "اختر منتجًا",
    summary: "ما ستنشئه",
    summaryProduct: "المنتج: {name}",
    summaryNoProduct: "بدون منتج بعد",
    summaryUpsell: "مع عرض بعد الشراء",
    summaryNoUpsell: "بدون عرض بعد الشراء",
    summaryLeads: "يجمع أرقام العملاء",
    created: "تم إنشاء «{name}».",
    createdPartial: "تم إنشاء مسار البيع لكن تعذّرت إضافة كل الصفحات المبدئية: {message}",
    productByHand: "مسار البيع جاهز، لكن لم يُكتب كل شيء ({message}). راجع المنتج في صفحاته من المحرر.",
    q1Missing: "اختر منتجًا، أو تابع بدون منتج.",
    steps: "خطوات الإنشاء",
    offerByHand: "مسار البيع جاهز، لكن العرض لم يصل إلى خطوة العرض. اختره هناك من المحرر.",
    planLimit: "ترقية الباقة",
    codeTitle: "نسخ مسار بيع بكود",
    codeBody: "الكود الذي أعطاه لك تاجر آخر. تحصل على صفحات المسار وروابطه بدون منتجاته أو طلباته.",
    code: "كود المشاركة",
    importIt: "نسخ المسار",
    importing: "جارٍ النسخ…",
    imported: "تم نسخ «{name}» — {steps} صفحات. اختر منتجاتك قبل النشر.",
    shareTitle: "مشاركة مسار البيع",
    shareDescription: "أعطِ هذا الكود لتاجر آخر. يحصل على نسخة من صفحات المسار وروابطه — بدون منتجاتك أو عروضك أو طلباتك.",
    shareStop: "إيقاف المشاركة",
    shareStopped: "تم إيقاف المشاركة. الكود القديم لم يعد يعمل.",
    shareCode: "مشاركة بكود",
    copy: "نسخ الكود",
    codeLoading: "جارٍ جلب الكود…",
    close: "إغلاق",
  },
} satisfies Messages;

export type WizardStrings = (typeof WIZARD_STRINGS)["en"];
