import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the funnels list (/funnels): the page, its stat cards, a row,
 * the row's menu and the confirmation. Arabic is the dashboard's formal
 * wording: «مسار البيع», «خطوة», «الطلب», «عرض بعد الشراء».
 */
export const FUNNEL_LIST_STRINGS = {
  en: {
    title: "Funnels",
    description: "A short path from an ad to an order: landing page, order form, an offer after the order, thank you.",
    newFunnel: "New funnel",
    // Stats
    stats: "All funnels in the period",
    kpiVisits: "Visits",
    kpiOrders: "Orders",
    kpiRevenue: "Revenue",
    kpiRevenueHint: "With offers after the order",
    kpiConversion: "Conversion",
    kpiConversionHint: "Orders ÷ visits",
    statsUnavailable: "The numbers couldn't be loaded",
    statsNoAccess: "Your role can't see the numbers. The store owner can give you the reports permission.",
    // Toolbar and chips
    search: "Search funnels",
    searchPlaceholder: "Funnel name",
    statuses: "Funnel status",
    all: "All",
    statusDraft: "Draft",
    statusPublished: "Live",
    statusPaused: "Paused",
    // Rows
    list: "Funnels",
    colFunnel: "Funnel",
    colStatus: "Status",
    colSteps: "Steps",
    colVisits: "Visits",
    colOrders: "Orders",
    colConversion: "Conv.",
    colRevenue: "Revenue",
    colUpdated: "Last edit",
    steps_one: "1 step",
    steps_other: "{n} steps",
    visits_one: "1 visit",
    visits_other: "{n} visits",
    orders_one: "1 order",
    orders_other: "{n} orders",
    edited: "Edited {date}",
    open: "Open",
    openFunnel: "Open “{name}”",
    menuLabel: "Actions for “{name}”",
    // Menu
    preview: "Preview",
    copyLink: "Copy the link",
    report: "Report",
    publish: "Publish",
    pause: "Pause",
    resume: "Resume",
    duplicate: "Duplicate",
    shareCode: "Share",
    delete: "Delete",
    // Toasts
    toastLive: "“{name}” is live.",
    toastPaused: "“{name}” paused.",
    toastResumed: "“{name}” is live again.",
    toastPublishBlocked: "“{name}” can't be published yet ({n} problems). Open it and fix them.",
    toastDuplicatedAs: "Copied as “{name}”.",
    toastDuplicatePartial: "The copy was made, but not every step or link came with it: {message}",
    toastCopied: "Link copied.",
    toastCopyFailed: "Couldn't copy.",
    toastDeleted: "“{name}” deleted.",
    copySuffix: "{name} (copy)",
    // Delete
    deleteTitle: "Delete “{name}”?",
    deleteDescription: "The funnel, its steps and its share link stop working immediately. Past orders are kept.",
    deleteConfirm: "Delete funnel",
    // Empty
    emptyTitle: "No funnels yet",
    emptyDescription: "A funnel takes a shopper from your ad to an order on one short path, and offers them something more after they order.",
    emptyAction: "Make your first funnel",
    noMatchTitle: "No funnel matches",
    noMatchBody: "Try another name or another status.",
    showAll: "Show all",
    // The create dialog
  },
  ar: {
    title: "مسارات البيع",
    description: "طريق قصير من الإعلان إلى الطلب: صفحة هبوط، ثم نموذج الطلب، ثم عرض بعد الشراء، ثم صفحة الشكر.",
    newFunnel: "مسار بيع جديد",
    stats: "كل مسارات البيع خلال الفترة",
    kpiVisits: "الجلسات",
    kpiOrders: "الطلبات",
    kpiRevenue: "الإيرادات",
    kpiRevenueHint: "شاملة عروض ما بعد الشراء",
    kpiConversion: "معدل التحويل",
    kpiConversionHint: "الطلبات ÷ الجلسات",
    statsUnavailable: "تعذّر تحميل الإحصاءات",
    statsNoAccess: "دورك لا يتيح عرض التحليلات. يستطيع مالك المتجر منحك صلاحية التقارير.",
    search: "ابحث في مسارات البيع",
    searchPlaceholder: "اسم مسار البيع",
    statuses: "حالة مسار البيع",
    all: "الكل",
    statusDraft: "مسودة",
    statusPublished: "منشور",
    statusPaused: "متوقف مؤقتًا",
    list: "مسارات البيع",
    colFunnel: "مسار البيع",
    colStatus: "الحالة",
    colSteps: "الخطوات",
    colVisits: "الزيارات",
    colOrders: "الطلبات",
    colConversion: "التحويل",
    colRevenue: "الإيرادات",
    colUpdated: "آخر تحديث",
    steps_one: "خطوة واحدة",
    steps_two: "خطوتان",
    steps_few: "{n} خطوات",
    steps_other: "{n} خطوة",
    visits_one: "زيارة واحدة",
    visits_two: "زيارتان",
    visits_few: "{n} زيارات",
    visits_other: "{n} زيارة",
    orders_one: "طلب واحد",
    orders_two: "طلبان",
    orders_few: "{n} طلبات",
    orders_other: "{n} طلبًا",
    edited: "عُدّل {date}",
    open: "فتح",
    openFunnel: "فتح «{name}»",
    menuLabel: "إجراءات «{name}»",
    preview: "معاينة",
    copyLink: "نسخ الرابط",
    report: "التحليلات",
    publish: "نشر",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    duplicate: "نسخ المسار",
    shareCode: "مشاركة",
    delete: "حذف",
    toastLive: "«{name}» منشور الآن.",
    toastPaused: "تم إيقاف «{name}» مؤقتًا.",
    toastResumed: "تم استئناف «{name}».",
    toastPublishBlocked: "لا يمكن نشر «{name}» بعد ({n} مشكلات). افتحه لإصلاحها.",
    toastDuplicatedAs: "تم النسخ باسم «{name}».",
    toastDuplicatePartial: "تم إنشاء النسخة لكن تعذّر نسخ بعض الخطوات أو الروابط: {message}",
    toastCopied: "تم نسخ الرابط.",
    toastCopyFailed: "تعذّر النسخ إلى الحافظة.",
    toastDeleted: "تم حذف «{name}».",
    copySuffix: "{name} (نسخة)",
    deleteTitle: "حذف «{name}»؟",
    deleteDescription: "سيتوقف مسار البيع وخطواته ورابط المشاركة عن العمل فورًا. الطلبات السابقة تبقى محفوظة.",
    deleteConfirm: "حذف مسار البيع",
    emptyTitle: "لا توجد مسارات بيع بعد",
    emptyDescription: "مسار البيع يأخذ العميل من إعلانك إلى الطلب في طريق واحد قصير، ويعرض عليه إضافة بعد أن يطلب.",
    emptyAction: "إنشاء أول مسار بيع",
    noMatchTitle: "لا يوجد مسار بيع مطابق",
    noMatchBody: "جرّب اسمًا آخر أو حالة أخرى.",
    showAll: "عرض الكل",
  },
} satisfies Messages;

export type FunnelListStrings = (typeof FUNNEL_LIST_STRINGS)["en"];
