import type { BlockedEntryScope } from "@store-builder/api-client";
import type { Messages } from "@/i18n/LocaleContext";

/** Every word of the Blocked tab: the tab, its rows and its two sheets read it through `useT(BLOCKED_STRINGS)`. */
export const BLOCKED_STRINGS = {
  en: {
    add: "Add",
    addLong: "Block something",
    importCsv: "Import",
    typeFilter: "Blocked entries by type",
    listLabel: "Blocked entries",
    all: "All",
    type_phone: "Phone",
    type_ip: "IP address",
    type_email: "Email",
    type_device: "Device",
    type_name_address: "Name + address",
    scope_orders: "Ordering",
    scope_otp: "Verification codes",
    scope_visit: "Visiting the store",
    scopeFilter: "Blocked from",
    scopeChip: "Blocked from: {scope}",
    showResults: "Show the results",
    search: "Search the blocked entries",
    searchPlaceholder: "Number, IP, name or reason",
    colValue: "Blocked",
    colScope: "Blocked from",
    colReason: "Reason",
    colAdded: "Added",
    noReason: "—",
    addedOn: "Added {date}",
    by: "by {name}",
    viewCustomer: "Open customer",
    remove: "Unblock",
    removeTitle: "Unblock {value}?",
    removeDescription: "It will no longer be blocked from this. A blocked phone's customer is un-blacklisted too.",
    removing: "Unblocking…",
    cancel: "Cancel",
    removed: "{value} is no longer blocked.",
    menuLabel: "Actions for this entry",
    menuCopy: "Copy it",
    copied: "Copied",
    emptyTitle: "Nothing is blocked yet",
    emptyDescription: "Block a phone, an IP, an email, a device or a name and address — from ordering, from verification codes, or from seeing the store.",
    emptyFiltered: "Nothing matches this search or these filters.",
    clearAll: "Clear the search and filters",
    addTitle: "Block something",
    addDescription: "Blocking something that is already blocked only updates its reason.",
    what: "What to block",
    value_phone: "Phone number",
    value_ip: "IP address",
    value_email: "Email address",
    value_device: "Device ID",
    name: "Customer name",
    address: "Address",
    nameAddressHint: "Matches orders with this name and this street address, however they are spaced or punctuated.",
    blockFrom: "Block from",
    reason: "Reason (optional)",
    reasonPlaceholder: "Refused three deliveries",
    valueRequired: "Fill this in.",
    valueInvalid_phone: "Enter a valid phone number.",
    valueInvalid_ip: "Enter a valid IP address.",
    valueInvalid_email: "Enter a valid email address.",
    valueInvalid_device: "A device ID is 8 to 128 characters.",
    valueInvalid_name_address: "Enter both a name and an address.",
    scopeRequired: "Choose at least one.",
    save: "Block",
    saving: "Blocking…",
    added: "{value} is now blocked.",
    importTitle: "Import a blocklist",
    importDescription:
      "A CSV file with one entry per line. With a header row, the columns are read by name: type, value, scope, reason, name, address. Without one, the first column is the value and the second the reason.",
    file: "CSV file",
    defaultType: "Type, for rows that do not say",
    defaultScope: "Block from, for rows that do not say",
    chooseFile: "Choose a file first.",
    fileTooBig: "The file is too large (1 MB at most).",
    runImport: "Import",
    importing: "Importing…",
    importDone: "{imported} added, {updated} already there, {skipped} skipped.",
    importErrors: "Lines that were skipped",
    line: "Line {n}: {message}",
    close: "Close",
  },
  ar: {
    add: "إضافة",
    addLong: "حظر جديد",
    importCsv: "استورد",
    typeFilter: "المحظورين حسب النوع",
    listLabel: "قايمة المحظورين",
    all: "الكل",
    type_phone: "رقم هاتف",
    type_ip: "عنوان IP",
    type_email: "بريد إلكتروني",
    type_device: "جهاز",
    type_name_address: "اسم + عنوان",
    scope_orders: "الطلب",
    scope_otp: "أكواد التحقق",
    scope_visit: "زيارة المتجر",
    scopeFilter: "محظور من",
    scopeChip: "محظور من: {scope}",
    showResults: "اعرض النتايج",
    search: "ابحث في المحظورين",
    searchPlaceholder: "رقم، IP، اسم أو سبب",
    colValue: "المحظور",
    colScope: "محظور من",
    colReason: "السبب",
    colAdded: "تاريخ الإضافة",
    noReason: "—",
    addedOn: "أُضيف {date}",
    by: "بواسطة {name}",
    viewCustomer: "فتح العميل",
    remove: "إلغاء الحظر",
    removeTitle: "إلغاء حظر {value}؟",
    removeDescription: "لن يبقى محظورًا من ذلك. وإذا كان رقم هاتف فسيُلغى حظر العميل صاحبه أيضًا.",
    removing: "جارٍ إلغاء الحظر…",
    cancel: "إلغاء",
    removed: "تم إلغاء حظر {value}.",
    menuLabel: "إجراءات المحظور",
    menuCopy: "نسخه",
    copied: "تم النسخ",
    emptyTitle: "لا يوجد أي محظور بعد",
    emptyDescription: "احظر رقم هاتف أو IP أو بريدًا أو جهازًا أو اسمًا وعنوانًا — من الطلب، أو من أكواد التحقق، أو من رؤية المتجر.",
    emptyFiltered: "لا توجد نتائج لهذا البحث أو هذه الفلاتر.",
    clearAll: "مسح البحث والفلاتر",
    addTitle: "حظر جديد",
    addDescription: "حظر شيء محظور بالفعل يحدّث السبب فقط.",
    what: "ما الذي تريد حظره",
    value_phone: "رقم الهاتف",
    value_ip: "عنوان IP",
    value_email: "البريد الإلكتروني",
    value_device: "معرّف الجهاز",
    name: "اسم العميل",
    address: "العنوان",
    nameAddressHint: "يطابق الطلبات التي تحمل هذا الاسم وهذا العنوان مهما اختلفت المسافات وعلامات الترقيم.",
    blockFrom: "الحظر من",
    reason: "السبب (اختياري)",
    reasonPlaceholder: "رفض الاستلام ثلاث مرات",
    valueRequired: "املأ هذا الحقل.",
    valueInvalid_phone: "أدخل رقم هاتف صحيحًا.",
    valueInvalid_ip: "أدخل عنوان IP صحيحًا.",
    valueInvalid_email: "أدخل بريدًا إلكترونيًا صحيحًا.",
    valueInvalid_device: "معرّف الجهاز من 8 إلى 128 حرفًا.",
    valueInvalid_name_address: "أدخل الاسم والعنوان معًا.",
    scopeRequired: "اختر واحدًا على الأقل.",
    save: "حظر",
    saving: "جارٍ الحظر…",
    added: "تم حظر {value}.",
    importTitle: "استيراد قائمة حظر",
    importDescription:
      "ملف CSV به إدخال محظور في كل سطر. إذا كان فيه صف عناوين تُقرأ الأعمدة بأسمائها: type, value, scope, reason, name, address. وإن لم يكن، فالعمود الأول هو القيمة والثاني هو السبب.",
    file: "ملف CSV",
    defaultType: "النوع للسطور التي لا تحدده",
    defaultScope: "الحظر من، للسطور التي لا تحدده",
    chooseFile: "اختر ملفًا أولًا.",
    fileTooBig: "الملف كبير جدًا (1 ميجابايت كحد أقصى).",
    runImport: "استيراد",
    importing: "جارٍ الاستيراد…",
    importDone: "أُضيف {imported}، {updated} موجود بالفعل، وتم تخطي {skipped}.",
    importErrors: "سطور تم تخطيها",
    line: "سطر {n}: {message}",
    close: "إغلاق",
  },
} satisfies Messages;

/** Isolates an LTR value (a phone, an IP) inside a sentence of either direction. */
export function isolate(value: string): string {
  return `\u2066${value}\u2069`;
}

/** The tone of the "blocked from" chip: ordering is the heavy one. */
export const SCOPE_TONE: Record<BlockedEntryScope, "danger" | "warning" | "neutral"> = {
  orders: "danger",
  otp: "warning",
  visit: "neutral",
};
