import type { Messages } from "@/i18n/LocaleContext";

/**
 * The words of the editor's shell: the toolbar, the two side panels, the
 * phone's bars and sheets, autosave, publish, the published versions and the
 * first-run steps. The shared pieces (inspector, library, look panel) keep
 * their own words in editorLocale.ts; these are read with `useT`, which in the
 * website editor is the same language (WebsiteEditorPage sets both).
 *
 * Counted words come in the plural forms lib/plural.ts reads (`pages_one`,
 * `pages_two`, `pages_few`, `pages_other`); English only uses two of them.
 */
export const SHELL_STRINGS = {
  en: {
    // --- toolbar ---
    toolbar: "Editor toolbar",
    back: "Back to your sites",
    statusPublished: "Published",
    statusDraft: "Draft",
    statusChanged: "Unpublished changes",
    statusSuspended: "Suspended",
    pageSwitcher: "Switch page: {name}",
    pagesTitle: "Pages",
    newPage: "New page",
    device: "Preview size",
    devicePhone: "Phone",
    deviceTablet: "Tablet",
    deviceDesktop: "Desktop",
    undo: "Undo",
    redo: "Redo",
    saveIdle: "All saved",
    saveSaved: "Saved just now",
    saveSaving: "Saving…",
    saveFailed: "Not saved — try again",
    saveShortIdle: "Saved",
    saveShortSaved: "Saved",
    saveShortSaving: "Saving…",
    saveShortFailed: "Not saved",
    more: "More",
    publish: "Publish",
    showSectionsPanel: "Show the sections panel",
    hideSectionsPanel: "Hide the sections panel",
    showEditPanel: "Show the editing panel",
    hideEditPanel: "Hide the editing panel",

    // --- the «…» menu ---
    menuPageSettings: "Page settings (SEO)",
    menuHistory: "Published versions",
    menuLiveStore: "Open your live store",
    menuStoreLook: "Store look",
    menuDark: "Preview in dark mode",
    menuLight: "Preview in light mode",
    menuXrayOn: "Show outlines",
    menuXrayOff: "Hide outlines",
    menuRefresh: "Reload the preview",

    // --- panels ---
    startPanel: "Sections and pages",
    endPanel: "Editing panel",
    tabSections: "Sections",
    tabPages: "Pages",
    panelTabs: "What the panel shows",
    addSection: "Add a section",
    lookTitle: "Store look",
    lookHint: "Tap anything in the store to edit it.",
    pageInfo: "This page",
    pagePath: "Address",

    // --- the phone ---
    dock: "Editing tools",
    dockSections: "Sections",
    dockAdd: "Add section",
    dockLook: "Look",
    dockEdit: "Edit: {name}",
    sectionsSheet: "Page sections",
    editSheet: "Edit",
    sheetGrow: "Make the panel taller",
    sheetShrink: "Make the panel shorter",
    sheetHide: "Put the panel away",

    // --- the look bar ---
    lookBar: "Look changes go live at once — save them?",
    lookSave: "Save the look",
    lookSaving: "Saving the look…",
    lookRevert: "Undo them",

    // --- saving ---
    saveErrorTitle: "Your last changes aren't saved yet.",
    retry: "Try again",
    leaveTitle: "Leave without saving?",
    leavePageBody: "Your last changes to this page couldn't be saved. If you leave now they are lost.",
    leaveLookBody: "Your look changes aren't saved. If you leave now they are lost.",
    leaveConfirm: "Leave",
    switchBody: "Your last changes to this page couldn't be saved. If you switch pages they are lost.",
    switchConfirm: "Switch page",

    // --- section actions ---
    sectionDeleted: "“{name}” deleted",
    sectionHidden: "“{name}” is hidden from your store",
    pickImage: "Choose a picture",

    // --- publish ---
    publishTitle: "Publish your site",
    publishFirst: "First publish: every page of the site goes live for your customers.",
    publishWhat: "What changes in your store",
    publishNothing: "No page content changed since the last publish.",
    publishAll: "Publishing puts every page live as it is now.",
    publishSeoNote: "A page's title and search settings go live with the publish too.",
    pageChanged: "Edited",
    pageNew: "New",
    removedPages_one: "1 deleted page leaves your store.",
    removedPages_two: "{n} deleted pages leave your store.",
    removedPages_few: "{n} deleted pages leave your store.",
    removedPages_other: "{n} deleted pages leave your store.",
    pages_one: "1 page",
    pages_two: "{n} pages",
    pages_few: "{n} pages",
    pages_other: "{n} pages",
    problemsTitle: "Fix these before publishing",
    problemNoHome: "The site has no home page at the address “/”. Add one.",
    problemEmpty: "This page is empty. Add a section with something in it.",
    openPage: "Open the page",
    lookPending: "Your look changes aren't saved yet — publishing doesn't include them.",
    checking: "Saving your last changes…",
    publishNow: "Publish now",
    publishing: "Publishing…",
    cancel: "Cancel",
    publishedToast: "Published — version {n} is live for your customers.",
    viewStore: "See your store",
    publishSaveFailed: "We couldn't save your last changes, so nothing was published. Try again.",

    // --- published versions ---
    historyTitle: "Published versions",
    historyHint: "Every publish keeps a version. You can put any of them back in front of your customers.",
    revision: "Version {n}",
    liveNow: "Live now",
    byYou: "You published it",
    byTeam: "Someone on your team published it",
    restore: "Restore this version",
    restoreTitle: "Restore version {n}?",
    restoreBody:
      "Your customers see this version at once. The draft you are editing does not change, and the store look (colours, header, footer) does not go back with it.",
    restoreConfirm: "Restore it",
    restoring: "Restoring…",
    restored: "Version {n} is live for your customers.",
    historyEmpty: "You haven't published this site yet. Your first publish shows up here.",
    keep: "Keep the current one",

    // --- first run ---
    guide: "Your first steps",
    guideTemplate: "Pick a template",
    guideBrand: "Make it yours",
    guidePublish: "Publish",
    guideDone: "done",
    guideDismiss: "Hide the steps",
    brandHint: "Pick a ready style and watch your store change. You can fine-tune the colours after.",
    brandMore: "All look settings",
  },
  ar: {
    // --- toolbar ---
    toolbar: "شريط المحرر",
    back: "العودة إلى المواقع",
    statusPublished: "منشور",
    statusDraft: "مسودة",
    statusChanged: "توجد تغييرات غير منشورة",
    statusSuspended: "موقوف",
    pageSwitcher: "تبديل الصفحة: {name}",
    pagesTitle: "الصفحات",
    newPage: "صفحة جديدة",
    device: "حجم المعاينة",
    devicePhone: "الهاتف",
    deviceTablet: "الجهاز اللوحي",
    deviceDesktop: "الحاسوب",
    undo: "تراجع",
    redo: "إعادة",
    saveIdle: "كل التعديلات محفوظة",
    saveSaved: "حُفظ للتو",
    saveSaving: "جارٍ الحفظ…",
    saveFailed: "لم يُحفظ — أعد المحاولة",
    saveShortIdle: "محفوظ",
    saveShortSaved: "حُفظ",
    saveShortSaving: "جارٍ الحفظ…",
    saveShortFailed: "لم يُحفظ",
    more: "المزيد",
    publish: "نشر",
    showSectionsPanel: "إظهار لوحة الأقسام",
    hideSectionsPanel: "إخفاء لوحة الأقسام",
    showEditPanel: "إظهار لوحة التعديل",
    hideEditPanel: "إخفاء لوحة التعديل",

    // --- the «…» menu ---
    menuPageSettings: "إعدادات الصفحة (محركات البحث)",
    menuHistory: "النسخ المنشورة",
    menuLiveStore: "فتح متجرك المنشور",
    menuStoreLook: "مظهر المتجر",
    menuDark: "معاينة الوضع الداكن",
    menuLight: "معاينة الوضع الفاتح",
    menuXrayOn: "إظهار حدود العناصر",
    menuXrayOff: "إخفاء حدود العناصر",
    menuRefresh: "تحديث المعاينة",

    // --- panels ---
    startPanel: "الأقسام والصفحات",
    endPanel: "لوحة التعديل",
    tabSections: "الأقسام",
    tabPages: "الصفحات",
    panelTabs: "ما تعرضه اللوحة",
    addSection: "إضافة قسم",
    lookTitle: "مظهر المتجر",
    lookHint: "اضغط على أي عنصر في المتجر لتعديله.",
    pageInfo: "هذه الصفحة",
    pagePath: "العنوان",

    // --- the phone ---
    dock: "أدوات التعديل",
    dockSections: "الأقسام",
    dockAdd: "إضافة قسم",
    dockLook: "المظهر",
    dockEdit: "تعديل: {name}",
    sectionsSheet: "أقسام الصفحة",
    editSheet: "تعديل",
    sheetGrow: "تكبير اللوحة",
    sheetShrink: "تصغير اللوحة",
    sheetHide: "إنزال اللوحة",

    // --- the look bar ---
    lookBar: "تغييرات المظهر تُنشر فور حفظها — هل تريد حفظها؟",
    lookSave: "حفظ المظهر",
    lookSaving: "جارٍ حفظ المظهر…",
    lookRevert: "تراجع",

    // --- saving ---
    saveErrorTitle: "آخر تعديلاتك لم تُحفظ بعد.",
    retry: "إعادة المحاولة",
    leaveTitle: "هل تريد الخروج دون حفظ؟",
    leavePageBody: "تعذّر حفظ آخر تعديلاتك في هذه الصفحة. إذا خرجت الآن فستفقدها.",
    leaveLookBody: "تغييرات المظهر لم تُحفظ بعد. إذا خرجت الآن فستفقدها.",
    leaveConfirm: "خروج",
    switchBody: "تعذّر حفظ آخر تعديلاتك في هذه الصفحة. إذا بدّلت الصفحة فستفقدها.",
    switchConfirm: "تبديل الصفحة",

    // --- section actions ---
    sectionDeleted: "حُذف «{name}»",
    sectionHidden: "أُخفي «{name}» من متجرك",
    pickImage: "اختيار صورة",

    // --- publish ---
    publishTitle: "نشر الموقع",
    publishFirst: "أول نشر: ستظهر كل صفحات الموقع لعملائك.",
    publishWhat: "ما سيتغيّر في متجرك",
    publishNothing: "لم يتغيّر محتوى الصفحات منذ آخر نشر.",
    publishAll: "النشر يُظهر كل صفحات الموقع كما هي الآن.",
    publishSeoNote: "عنوان الصفحة وإعدادات محركات البحث تُنشر مع النشر أيضًا.",
    pageChanged: "عُدّلت",
    pageNew: "جديدة",
    removedPages_one: "صفحة واحدة حُذفت وستختفي من متجرك.",
    removedPages_two: "صفحتان حُذفتا وستختفيان من متجرك.",
    removedPages_few: "{n} صفحات حُذفت وستختفي من متجرك.",
    removedPages_other: "{n} صفحة حُذفت وستختفي من متجرك.",
    pages_one: "صفحة واحدة",
    pages_two: "صفحتان",
    pages_few: "{n} صفحات",
    pages_other: "{n} صفحة",
    problemsTitle: "أصلح ما يلي قبل النشر",
    problemNoHome: "ليس للموقع صفحة رئيسية على العنوان «/». أضف واحدة.",
    problemEmpty: "هذه الصفحة فارغة. أضف قسمًا فيه محتوى.",
    openPage: "فتح الصفحة",
    lookPending: "تغييرات المظهر لم تُحفظ بعد — النشر لا يشملها.",
    checking: "جارٍ حفظ آخر تعديلاتك…",
    publishNow: "انشر الآن",
    publishing: "جارٍ النشر…",
    cancel: "إلغاء",
    publishedToast: "تم النشر — النسخة {n} تظهر الآن لعملائك.",
    viewStore: "عرض متجرك",
    publishSaveFailed: "تعذّر حفظ آخر تعديلاتك، فلم يُنشر شيء. أعد المحاولة.",

    // --- published versions ---
    historyTitle: "النسخ المنشورة",
    historyHint: "كل نشر يحتفظ بنسخة. يمكنك إعادة أي نسخة منها لتظهر لعملائك.",
    revision: "النسخة {n}",
    liveNow: "تظهر للعملاء الآن",
    byYou: "نشرتَها أنت",
    byTeam: "نشرها أحد أعضاء فريقك",
    restore: "استعادة هذه النسخة",
    restoreTitle: "استعادة النسخة {n}؟",
    restoreBody:
      "سيرى عملاؤك هذه النسخة فورًا. المسودة التي تعدّلها لا تتغيّر، ومظهر المتجر (الألوان والترويسة والتذييل) لا يعود معها.",
    restoreConfirm: "استعادة",
    restoring: "جارٍ الاستعادة…",
    restored: "النسخة {n} تظهر الآن لعملائك.",
    historyEmpty: "لم تنشر هذا الموقع بعد. أول نشر سيظهر هنا.",
    keep: "إبقاء الحالية",

    // --- first run ---
    guide: "خطواتك الأولى",
    guideTemplate: "اختر القالب",
    guideBrand: "اجعله بهويتك",
    guidePublish: "انشر",
    guideDone: "أنجزتها",
    guideDismiss: "إخفاء الخطوات",
    brandHint: "اختر مظهرًا جاهزًا وشاهد متجرك يتغيّر، ثم اضبط الألوان كما تريد.",
    brandMore: "كل إعدادات المظهر",
  },
} satisfies Messages;

export type ShellStrings = Record<keyof (typeof SHELL_STRINGS)["en"], string>;
