import type { ConfirmationAttemptSource, ConfirmationOutcome } from "@store-builder/api-client";
import { useT, type Messages } from "@/i18n/LocaleContext";

/**
 * The confirmation queue's shared words: the page chrome, the list view's
 * cards, the outcome names, the toasts, and the actions on several orders at
 * once. The calling station keeps its own table beside its files
 * (station/stationStrings.ts).
 */
export const QUEUE_STRINGS = {
  en: {
    title: "Confirmation queue",
    description: "Call each customer to confirm their order before it moves to fulfilment.",
    tabsLabel: "Queue tabs",
    tabPending: "Pending",
    tabInProgress: "In progress",
    tabDone: "Done",
    viewLabel: "How the queue is shown",
    viewStation: "One by one",
    viewList: "List",
    emptyPending: "No orders are waiting for confirmation right now.",
    emptyInProgress: "Nobody is on a call right now.",
    emptyDone: "No finished confirmations yet.",
    outcomeConfirmed: "Confirmed",
    outcomeRejected: "Rejected",
    outcomeUnreachable: "Unreachable",
    outcomePostponed: "Postponed",
    outcomesLabel: "What happened on the call?",
    itemsHeading: "What is in the order",
    moreItems: "+{n} more",
    times: "× {n}",
    attemptsOne: "1 previous attempt",
    attemptsOther: "{n} previous attempts",
    unnamedCustomer: "Unnamed customer",
    noPhone: "No phone number",
    pickup: "Pickup from the store — no delivery",
    paymentFirst: "Review the payment first: an order paid by transfer is confirmed only once its payment is approved.",
    claiming: "Claiming…",
    claimAndCall: "Claim & call",
    claimOnly: "Claim",
    takeOver: "Take over",
    reclaim: "Claim again",
    release: "Release",
    releasing: "Releasing…",
    rejectionReason: "Rejection reason",
    rejectionPlaceholder: "Customer changed their mind",
    notes: "Notes",
    notesPlaceholder: "Anything worth recording from the call (optional).",
    saving: "Saving…",
    saveOutcome: "Save & next",
    toastMarked: "{order} marked {outcome}.",
    toastReleased: "{order} is back in Pending.",
    callbackDue: "Callback due since {time}",
    callbackLater: "Callback scheduled for {time}",
    waitingTitle: "Waiting for the offers window",
    waitingBody:
      "The customer is still on the sales funnel's offers and may add to this order. It opens for confirmation in {left} (at {time}), with its final total.",
    waitingSoon: "The customer is still on the sales funnel's offers. It opens for confirmation in a moment.",
    waitingCount: "{n} waiting for the offers window",
    lastAttempt: "Last: {outcome} by {agent}, {time}",
    yourClaim: "You're on this call · {left} left",
    yourClaimExpired: "Your claim expired. Claim it again before saving — someone else may take it.",
    heldBy: "{name} is on this call · {left} left",
    heldByExpired: "{name}'s claim expired — anyone can take it over.",
    someone: "Another agent",
    lockedBy: "{name} is already on this call ({left} left).",
    doneAt: "{outcome} · {time}",
    doneBy: "by {agent}",
    orderCancelled: "Order cancelled",
    orderDetails: "Order details",
    history: "History ({n})",
    sourceQueue: "call",
    sourceOrderPage: "order page",
    sourceCorrection: "correction",
    corrected: "{from} → {to}",
    unknownAgent: "Unknown user",
    correct: "Correct outcome",
    correctTitle: "Correct {order}",
    correctToRejected:
      "Change to Rejected. Any courier booking that hasn't been collected is cancelled and the stock is released.",
    correctToConfirmed: "Change to Confirmed. The stock is reserved again; this fails if it has sold out.",
    correctReason: "Reason",
    correctReasonPlaceholder: "Customer called back",
    correctNotes: "Notes (optional)",
    correctSubmit: "Change to {outcome}",
    cancel: "Cancel",
    toastCorrected: "{order} changed to {outcome}.",
    filtersTitle: "Sort and filter",
    showCount: "Show {count}",
    showAll: "Show the queue",
    activeFilters: "Filters in effect",
    removeFilter: "Remove: {label}",
    clearAll: "Clear all",
    sortLabel: "Sort",
    sortChip: "Sort: {label}",
    sort_default: "Queue order",
    sort_newest: "Newest first",
    sort_oldest: "Oldest first",
    sort_total_desc: "Total: high to low",
    sort_total_asc: "Total: low to high",
    assignmentFilter: "Assignment",
    assignShow: "Assign",
    assignChange: "Change",
    filterAll: "All tasks",
    filterMine: "Assigned to me",
    filterUnassigned: "Unassigned",
    filterAgents: "Assigned to an agent",
    assignedTo: "Assigned to {name}",
    assignedToYou: "Assigned to you",
    notAssigned: "Not assigned",
    assignTo: "Assign {order} to",
    nobody: "Nobody (open to all)",
    assignedToast: "{order} assigned to {name}.",
    unassignedToast: "{order} is open to every agent again.",
    assignedToOther: "Assigned to {name}. Only they or a manager can take it.",
    selectTask: "Select {order}",
    selectAll: "Select all shown ({n})",
    allSelected: "Everything shown is selected.",
    sel_one: "1 selected",
    sel_other: "{n} selected",
    bulkAgent: "Agent for the selected tasks",
    bulkAssign: "Assign",
    bulkAssignTitle: "Assign {count} to",
    bulkAssignHint: "Pick an agent. Only they or a manager can then take these calls.",
    bulkUnassign: "Remove assignment",
    bulkDone: "{n} tasks updated.",
    bulkSkipped: "{n} finished tasks were left as they were.",
    bulkAccept: "Accept all selected",
    bulkCancel: "Cancel all selected",
    acceptTitle: "Accept {count}?",
    cancelTitle: "Cancel {count}?",
    acceptBody:
      "Each of these orders is recorded as Confirmed and moves on to fulfilment, without a call to the customer. Use it only for orders you have already checked.",
    cancelBody:
      "Each of these orders is recorded as Rejected: it is not shipped and its stock goes back on sale. A manager can correct an order from the Done tab afterwards, as long as it has not shipped.",
    bulkLeftOut: "Left as they are",
    bulkLeftPayment: "{count} paid by transfer whose payment is not approved yet",
    bulkLeftHeld: "{count} a teammate is on right now",
    bulkNothing: "None of the selected orders can take this now.",
    bulkReason: "Reason for the cancellation",
    bulkReasonHint: "Saved on every one of these orders.",
    bulkContinue: "Continue",
    bulkClose: "Close",
    bulkBack: "Back",
    againTitle: "Are you sure?",
    acceptAgain: "{count} will be confirmed now, in one go. This is not undone with one press.",
    cancelAgain: "{count} will be cancelled now, in one go. This is not undone with one press.",
    acceptYes: "Yes, accept {count}",
    cancelYes: "Yes, cancel {count}",
    bulkWorkingTitle: "Working on it…",
    bulkProgress: "{done} of {total}",
    bulkKeepOpen: "Keep this window open until it finishes.",
    bulkResultTitle: "Finished",
    bulkAccepted: "{count} accepted.",
    bulkCancelled: "{count} cancelled.",
    bulkNoneDone: "Nothing was changed.",
    bulkFailed: "{count} left as they were:",
    bulkGone: "It already has a result.",
    bulkNote: "Recorded for several orders at once from the confirmation queue.",
    via: "via {channel}",
    answerNone: "No calls waiting. New cash-on-delivery orders land here by themselves.",
    answer_one: "1 call left",
    answer_other: "{n} calls left",
    answerDue: "{n} of them are due now",
    answerMine: "you are on {n}",
    lockSoon: "Only {left} left on your claim — save the result now.",
    emptyAction: "See all orders",
  },
  ar: {
    title: "قائمة التأكيد",
    description: "اتصل بكل عميل لتأكيد طلبه قبل أن ينتقل إلى التجهيز.",
    tabsLabel: "أقسام القائمة",
    tabPending: "بالانتظار",
    tabInProgress: "قيد التنفيذ",
    tabDone: "منتهية",
    viewLabel: "طريقة عرض القائمة",
    viewStation: "طلب بعد طلب",
    viewList: "القائمة",
    emptyPending: "لا توجد طلبات بانتظار التأكيد حاليًا.",
    emptyInProgress: "لا أحد في مكالمة الآن.",
    emptyDone: "لا توجد تأكيدات منتهية بعد.",
    outcomeConfirmed: "مؤكد",
    outcomeRejected: "مرفوض",
    outcomeUnreachable: "تعذّر الوصول",
    outcomePostponed: "مؤجل",
    outcomesLabel: "ما نتيجة المكالمة؟",
    itemsHeading: "محتويات الطلب",
    moreItems: "+{n} أخرى",
    times: "× {n}",
    attemptsOne: "محاولة سابقة واحدة",
    attemptsOther: "{n} محاولات سابقة",
    unnamedCustomer: "عميل بدون اسم",
    noPhone: "لا يوجد رقم هاتف",
    pickup: "استلام من المتجر — بدون توصيل",
    paymentFirst: "راجع الدفع أولًا: الطلب المدفوع بالتحويل لا يُؤكَّد إلا بعد قبول دفعه.",
    claiming: "جارٍ الاستلام…",
    claimAndCall: "استلام واتصال",
    claimOnly: "استلام",
    takeOver: "استلام بدلًا منه",
    reclaim: "استلام مرة أخرى",
    release: "إرجاع للقائمة",
    releasing: "جارٍ الإرجاع…",
    rejectionReason: "سبب الرفض",
    rejectionPlaceholder: "غيّر العميل رأيه",
    notes: "ملاحظات",
    notesPlaceholder: "أي شيء يستحق التسجيل من المكالمة (اختياري).",
    saving: "جارٍ الحفظ…",
    saveOutcome: "حفظ والتالي",
    toastMarked: "تم تعيين {order} كـ {outcome}.",
    toastReleased: "عاد {order} إلى قائمة الانتظار.",
    callbackDue: "موعد معاودة الاتصال حان منذ {time}",
    callbackLater: "معاودة الاتصال مجدولة في {time}",
    waitingTitle: "في انتظار نافذة العروض",
    waitingBody:
      "ما زال العميل في عروض مسار البيع وقد يضيف إلى هذا الطلب. يُتاح للتأكيد خلال {left} (في {time}) بإجماليه النهائي.",
    waitingSoon: "ما زال العميل في عروض مسار البيع. يُتاح الطلب للتأكيد بعد لحظات.",
    waitingCount: "{n} في انتظار نافذة العروض",
    lastAttempt: "آخر محاولة: {outcome} بواسطة {agent}، {time}",
    yourClaim: "أنت في هذه المكالمة · المتبقي {left}",
    yourClaimExpired: "انتهت مدة استلامك. استلمه مرة أخرى قبل الحفظ — قد يستلمه شخص آخر.",
    heldBy: "{name} في هذه المكالمة · المتبقي {left}",
    heldByExpired: "انتهت مدة استلام {name} — يمكن لأي شخص استلامه.",
    someone: "موظف آخر",
    lockedBy: "{name} في هذه المكالمة بالفعل (المتبقي {left}).",
    doneAt: "{outcome} · {time}",
    doneBy: "بواسطة {agent}",
    orderCancelled: "طلب ملغي",
    orderDetails: "تفاصيل الطلب",
    history: "السجل ({n})",
    sourceQueue: "مكالمة",
    sourceOrderPage: "صفحة الطلب",
    sourceCorrection: "تصحيح",
    corrected: "{from} ← {to}",
    unknownAgent: "مستخدم غير معروف",
    correct: "تصحيح النتيجة",
    correctTitle: "تصحيح {order}",
    correctToRejected: "التغيير إلى مرفوض. تُلغى أي شحنة لم تُستلم بعد ويُحرَّر المخزون.",
    correctToConfirmed: "التغيير إلى مؤكد. يُحجز المخزون مرة أخرى، ويفشل ذلك إذا نفد.",
    correctReason: "السبب",
    correctReasonPlaceholder: "اتصل العميل مرة أخرى",
    correctNotes: "ملاحظات (اختياري)",
    correctSubmit: "التغيير إلى {outcome}",
    cancel: "إلغاء",
    toastCorrected: "تم تغيير {order} إلى {outcome}.",
    filtersTitle: "الترتيب والتصفية",
    showCount: "عرض {count}",
    showAll: "عرض القائمة",
    activeFilters: "عوامل التصفية المفعّلة",
    removeFilter: "إزالة: {label}",
    clearAll: "إزالة الكل",
    sortLabel: "الترتيب",
    sortChip: "الترتيب: {label}",
    sort_default: "ترتيب القائمة",
    sort_newest: "الأحدث أولًا",
    sort_oldest: "الأقدم أولًا",
    sort_total_desc: "الإجمالي: من الأعلى إلى الأقل",
    sort_total_asc: "الإجمالي: من الأقل إلى الأعلى",
    assignmentFilter: "التعيين",
    assignShow: "تعيين",
    assignChange: "تغيير",
    filterAll: "الكل",
    filterMine: "طلباتي",
    filterUnassigned: "غير معيّنة",
    filterAgents: "معيّنة لموظف",
    assignedTo: "المعيّن له: {name}",
    assignedToYou: "المعيّن له: أنت",
    notAssigned: "غير معيّن",
    assignTo: "تعيين {order} إلى",
    nobody: "لا أحد (متاح للجميع)",
    assignedToast: "تم تعيين {order} إلى {name}.",
    unassignedToast: "أصبح {order} متاحًا لجميع الموظفين.",
    assignedToOther: "معيّن لـ {name}، ولا يستلمه غيره إلا المدير.",
    selectTask: "تحديد {order}",
    selectAll: "تحديد كل المعروض ({n})",
    allSelected: "كل المعروض محدد.",
    sel_one: "طلب واحد محدد",
    sel_two: "طلبان محددان",
    sel_few: "{n} طلبات محددة",
    sel_other: "{n} طلبًا محددًا",
    bulkAgent: "الموظف للمهام المحددة",
    bulkAssign: "تعيين",
    bulkAssignTitle: "تعيين {count} إلى",
    bulkAssignHint: "اختر موظفًا. بعدها لا يستلم هذه المكالمات إلا هو أو المدير.",
    bulkUnassign: "إزالة التعيين",
    bulkDone: "تم تحديث {n} من المهام.",
    bulkSkipped: "تُركت {n} من المهام المنتهية كما هي.",
    bulkAccept: "قبول كل الطلبات المحددة",
    bulkCancel: "إلغاء كل الطلبات المحددة",
    acceptTitle: "قبول {count}؟",
    cancelTitle: "إلغاء {count}؟",
    acceptBody:
      "يُسجَّل كل طلب من هذه الطلبات على أنه «مؤكد» وينتقل إلى التجهيز دون اتصال بالعميل. استخدم هذا الإجراء للطلبات التي راجعتها بالفعل فقط.",
    cancelBody:
      "يُسجَّل كل طلب من هذه الطلبات على أنه «مرفوض»: لا يُشحن ويعود مخزونه متاحًا للبيع. يمكن للمدير تصحيح نتيجة أي طلب بعد ذلك من قسم «منتهية» ما دام لم يُشحن.",
    bulkLeftOut: "تبقى كما هي",
    bulkLeftPayment: "{count} مدفوعة بالتحويل ولم يُقبل دفعها بعد",
    bulkLeftHeld: "{count} يعمل عليها زميل الآن",
    bulkNothing: "لا يوجد بين الطلبات المحددة طلب يقبل هذا الإجراء الآن.",
    bulkReason: "سبب الإلغاء",
    bulkReasonHint: "يُحفظ على كل طلب من هذه الطلبات.",
    bulkContinue: "متابعة",
    bulkClose: "إغلاق",
    bulkBack: "رجوع",
    againTitle: "هل أنت متأكد؟",
    acceptAgain: "سيُؤكَّد {count} الآن دفعة واحدة، ولا يمكن التراجع عن ذلك بضغطة واحدة.",
    cancelAgain: "سيُلغى {count} الآن دفعة واحدة، ولا يمكن التراجع عن ذلك بضغطة واحدة.",
    acceptYes: "نعم، اقبل {count}",
    cancelYes: "نعم، ألغِ {count}",
    bulkWorkingTitle: "جارٍ التنفيذ…",
    bulkProgress: "{done} من {total}",
    bulkKeepOpen: "أبقِ هذه النافذة مفتوحة حتى ينتهي التنفيذ.",
    bulkResultTitle: "انتهى التنفيذ",
    bulkAccepted: "تم قبول {count}.",
    bulkCancelled: "تم إلغاء {count}.",
    bulkNoneDone: "لم يتغيّر شيء.",
    bulkFailed: "تُرك {count} كما هو:",
    bulkGone: "سُجّلت نتيجته من قبل.",
    bulkNote: "سُجّلت النتيجة لعدة طلبات دفعة واحدة من قائمة التأكيد.",
    via: "عبر {channel}",
    answerNone: "لا توجد مكالمات بانتظارك. طلبات الدفع عند الاستلام الجديدة تظهر هنا تلقائيًا.",
    answer_one: "تبقّت مكالمة واحدة",
    answer_two: "تبقّت مكالمتان",
    answer_few: "تبقّت {n} مكالمات",
    answer_other: "تبقّت {n} مكالمة",
    answerDue: "حان موعد {n} منها",
    answerMine: "أنت تعمل على {n}",
    lockSoon: "تبقّى {left} فقط على استلامك — احفظ النتيجة الآن.",
    emptyAction: "عرض كل الطلبات",
  },
} satisfies Messages;

export type QueueStrings = Record<keyof typeof QUEUE_STRINGS.en, string>;

export function useQueueStrings(): QueueStrings {
  return useT(QUEUE_STRINGS);
}

/** Outcome names for the list's toggles, the done cards and the toasts, in the active locale. */
export function useOutcomeLabels(): Record<ConfirmationOutcome, string> {
  const t = useT(QUEUE_STRINGS);
  return {
    confirmed: t.outcomeConfirmed,
    rejected: t.outcomeRejected,
    unreachable: t.outcomeUnreachable,
    postponed: t.outcomePostponed,
  };
}

export function sourceLabel(t: QueueStrings, source: ConfirmationAttemptSource): string {
  if (source === "order_page") return t.sourceOrderPage;
  if (source === "correction") return t.sourceCorrection;
  return t.sourceQueue;
}
