import { useT, type Messages } from "@/i18n/LocaleContext";

/** The calling station's own words. Outcome names for toasts and the list stay in ../queueStrings.ts. */
export const STATION_STRINGS = {
  en: {
    stationLabel: "Calling station",
    cardLabel: "Order {order} from {name}",
    nextUp: "Next: {name}",
    progress: "{done} of {total}",
    progressLabel: "Calls done this sitting: {done} of {total}",
    attempt: "Attempt {n}",
    lockShort: "{n} min",
    lockExpired: "Your claim ran out — it is taken again when you record a result.",
    openOrderNumber: "Open order {order}",
    phoneHidden: "Part of the number is hidden",
    historyLabel: "Their history with the store",
    firstOrder: "Their first order",
    before: "{orders} before this",
    beforeRejected: "{orders} before this — rejected {n}",
    flaggedNumber: "Number is flagged",
    reliability: "Reliability {n} of {max}",
    receives: "Takes delivery of {rate}",
    receivesTitle: "Across every store on the platform: delivered {delivered} of {finished} orders.",
    deposit: "Ask for a deposit",
    depositTitle: "Low delivery rate: ask for a deposit or for the shipping fee upfront.",
    spam_one: "1 report from another store",
    spam_other: "{n} reports from other stores",
    moreFlags: "+{n}",
    offer: "Offer: {name}",
    total: "Total",
    placed: "Placed {when}",
    placedLate: "Placed {when} — waiting for more than {hours}",
    noAddress: "No shipping address",
    assignedYou: "Assigned to you",
    assignedTo: "Assigned to {name}",
    lastNote: "Note from the last call",
    contactLabel: "Reach the customer",
    outcomesLabel: "What happened?",
    call: "Call",
    whatsapp: "WhatsApp",
    used: "used on this call",
    confirmed: "Confirmed",
    noAnswer: "No answer",
    later: "Call later",
    cancelled: "Cancelled",
    skip: "Skip",
    skipLabel: "Skip to the next order without a result",
    note: "Note",
    noteAdded: "Note added",
    openOrder: "Open the order to edit it",
    keyEnter: "Enter",
    sheetFor: "{name} · {order}",
    laterTitle: "Call later",
    laterHint: "The order comes back to the queue in 24 hours.",
    cancelTitle: "The customer cancelled",
    cancelSave: "Record the cancellation",
    noteTitle: "A note on this call",
    noteHint: "It is saved with the result you record next.",
    noteDone: "Done",
    back: "Back",
    takenBy: "{name} got to this order first — moved on to the next one.",
    takenAssigned: "This order is assigned to {name} — moved on to the next one.",
    takenDone: "This order already has its result — moved on to the next one.",
    loadingNext: "Getting the next order…",
    doneTitle: "Calls are done",
    noneDue: "No calls for you right now",
    doneConfirmed: "You confirmed {orders} this sitting. New cash-on-delivery orders land here by themselves.",
    doneLogged: "You logged {calls} this sitting. New cash-on-delivery orders land here by themselves.",
    bookedLabel: "Booked for later",
    later_one: "1 call is booked for later",
    later_other: "{n} calls are booked for later",
    nearest: "next at {time}",
    others_one: "1 call is with a teammate now",
    others_other: "{n} calls are with teammates now",
    filtered: "A filter is on, so some calls may not be showing.",
    clearFilters: "Clear the filters",
    refresh: "Check for new orders",
    showList: "Open the list",
  },
  ar: {
    stationLabel: "محطة المكالمات",
    cardLabel: "الطلب {order} من {name}",
    nextUp: "التالي: {name}",
    progress: "{done} من {total}",
    progressLabel: "المكالمات المنجزة في هذه الجلسة: {done} من {total}",
    attempt: "المحاولة {n}",
    lockShort: "{n} د",
    lockExpired: "انتهت مدة استلامك — يُستلم الطلب مرة أخرى عند تسجيل النتيجة.",
    openOrderNumber: "فتح الطلب {order}",
    phoneHidden: "جزء من الرقم مخفي",
    historyLabel: "سجله مع المتجر",
    firstOrder: "أول طلب له",
    before: "{orders} قبل هذا",
    beforeRejected: "{orders} قبل هذا — رُفض منها {n}",
    flaggedNumber: "رقم عليه علامة تحذير",
    reliability: "درجة الموثوقية {n} من {max}",
    receives: "نسبة الاستلام {rate}",
    receivesTitle: "في جميع متاجر المنصة: استلم {delivered} من أصل {finished} طلب.",
    deposit: "اطلب عربونًا",
    depositTitle: "نسبة استلامه منخفضة: اطلب عربونًا أو رسوم الشحن مقدمًا.",
    spam_one: "بلاغ واحد من متجر آخر",
    spam_two: "بلاغان من متاجر أخرى",
    spam_few: "{n} بلاغات من متاجر أخرى",
    spam_other: "{n} بلاغًا من متاجر أخرى",
    moreFlags: "+{n}",
    offer: "عرض: {name}",
    total: "الإجمالي",
    placed: "طُلب {when}",
    placedLate: "طُلب {when} — ينتظر منذ أكثر من {hours}",
    noAddress: "لا يوجد عنوان شحن",
    assignedYou: "معيّن لك",
    assignedTo: "المعيّن له: {name}",
    lastNote: "ملاحظة من آخر مكالمة",
    contactLabel: "التواصل مع العميل",
    outcomesLabel: "ما النتيجة؟",
    call: "اتصال",
    whatsapp: "واتساب",
    used: "استُخدم في هذه المكالمة",
    confirmed: "تم التأكيد",
    noAnswer: "لم يرد",
    later: "اتصال لاحقًا",
    cancelled: "أُلغي",
    skip: "تخطّي",
    skipLabel: "الانتقال إلى الطلب التالي دون تسجيل نتيجة",
    note: "ملاحظة",
    noteAdded: "أُضيفت ملاحظة",
    openOrder: "فتح الطلب لتعديله",
    keyEnter: "Enter",
    sheetFor: "{name} · {order}",
    laterTitle: "اتصال لاحقًا",
    laterHint: "يعود الطلب إلى القائمة بعد 24 ساعة.",
    cancelTitle: "ألغى العميل الطلب",
    cancelSave: "تسجيل الإلغاء",
    noteTitle: "ملاحظة على هذه المكالمة",
    noteHint: "تُحفظ مع النتيجة التي تسجّلها بعدها.",
    noteDone: "تم",
    back: "رجوع",
    takenBy: "سبقك {name} إلى هذا الطلب — انتقلنا إلى التالي.",
    takenAssigned: "هذا الطلب معيّن لـ {name} — انتقلنا إلى التالي.",
    takenDone: "سُجّلت نتيجة هذا الطلب من قبل — انتقلنا إلى التالي.",
    loadingNext: "جارٍ إحضار الطلب التالي…",
    doneTitle: "انتهت المكالمات",
    noneDue: "لا توجد مكالمات لك الآن",
    doneConfirmed: "أكّدت {orders} في هذه الجلسة. طلبات الدفع عند الاستلام الجديدة تظهر هنا تلقائيًا.",
    doneLogged: "سجّلت {calls} في هذه الجلسة. طلبات الدفع عند الاستلام الجديدة تظهر هنا تلقائيًا.",
    bookedLabel: "مؤجّلة إلى وقت لاحق",
    later_one: "مكالمة واحدة موعدها لاحقًا",
    later_two: "مكالمتان موعدهما لاحقًا",
    later_few: "{n} مكالمات موعدها لاحقًا",
    later_other: "{n} مكالمة موعدها لاحقًا",
    nearest: "أقربها {time}",
    others_one: "مكالمة واحدة مع زميل الآن",
    others_two: "مكالمتان مع زملائك الآن",
    others_few: "{n} مكالمات مع زملائك الآن",
    others_other: "{n} مكالمة مع زملائك الآن",
    filtered: "يوجد عامل تصفية مفعّل، فقد لا تظهر بعض المكالمات.",
    clearFilters: "إزالة عوامل التصفية",
    refresh: "التحقق من وجود طلبات جديدة",
    showList: "فتح القائمة",
  },
} satisfies Messages;

export type StationStrings = Record<keyof typeof STATION_STRINGS.en, string>;

export function useStationStrings(): StationStrings {
  return useT(STATION_STRINGS);
}
