import type { Locale, Messages } from "@/i18n/LocaleContext";
import type { UiEdgeCondition, UiStepType } from "../funnelAdapter";

/**
 * The words of the funnel editor's two side panes: the steps list and the
 * step inspector (editor/StepsPane.tsx, editor/StepInspector.tsx,
 * GenericPagesPanel.tsx). The English of "Name" and "Fix before publishing"
 * is what FunnelEditorPage.test.tsx looks for.
 */
export const PANE_STRINGS = {
  en: {
    // The steps list.
    steps: "Steps",
    addStep: "Add step",
    addStepTitle: "Add which step?",
    addStepHint: "It is added after the selected step, or at the end of the funnel.",
    collapse: "Hide the steps list",
    reorder: "Move {name} in the list",
    rowMenu: "Actions for {name}",
    openPage: "Open the page",
    rename: "Rename",
    duplicate: "Duplicate",
    remove: "Delete",
    toFix: "{n} to fix",
    noSteps: "No steps yet. Add the first one, or pick a template on the map.",
    reorderNote: "Dragging here only changes the order of this list. The path a shopper walks is the arrows on the map.",
    reorderNoteOk: "Got it",

    // The inspector.
    stepSettings: "Step settings",
    close: "Close step settings",
    problems: "Fix before publishing",
    name: "Name",
    nameEmpty: "Give the step a name so you can tell it apart.",
    key: "Step key",
    copyKey: "Copy the step key",
    type: "Type",
    typeTitle: "Change the step's type",
    typeHint: "The page and the ways out stay as they are.",
    offer: "Offer",
    product: "Product",
    pickProduct: "Pick a product",
    offerLabel: "Offer",
    pickOffer: "Pick an offer",
    noOffers: "This product has no active offer. Add one on the product's page.",
    noProducts: "No products yet. Add a product and an offer first.",
    offersError: "We couldn't load the offers. Check the connection and open the step again.",
    offersLoading: "Loading the offers…",
    required: "Required before publishing.",
    offerMissing: "The offer is gone or switched off. Pick another one.",
    offerPrice: "Offer price",
    offerPriceNone: "Uses the variant prices",
    bump: "Checkout add-on offer",
    bumpHint: "Optional. A tick box on this step's order form — “Add to your order” — that goes into the same order.",
    bumpLabel: "Add-on offer",
    after: "After this step",
    afterHint: "Where the shopper goes next.",
    addWay: "Add a way out",
    noWays: "No way out yet. Add one, or this step ends the funnel.",
    thankYouEnds: "The thank-you page ends the funnel.",
    needOtherStep: "Add another step first, then link this one to it.",
    wayWhen: "When",
    wayTo: "Goes to",
    wayToOption: "{name}",
    wayGone: "That step was deleted. Pick another one.",
    pickStep: "Pick a step",
    removeWay: "Remove this way out",
    priority: "Priority",
    priorityHint: "With two ways that both fit, the higher number wins.",
    otherConditions: "Other conditions",
    sameCondition: "Two ways out share a condition. The shopper takes the one with the higher priority.",
    noDecline: "No way out for a shopper who says no. Add one, or they stop here.",
    noAccept: "No way out for a shopper who says yes. Add one, or they stop here.",
    whenButton: "When they press “{label}”",
    page: "Page",
    pageEmpty: "The page is empty. Add something before publishing.",
    pageCount: "{sections} · {elements}",
    section_one: "1 section",
    section_other: "{n} sections",
    element_one: "1 element",
    element_other: "{n} elements",
    testRunning: "A test is running on this step",
    testNamed: "“{name}” is showing two versions of this page.",
    openTests: "Open tests",
    addNext: "Add the next step",
    addNextTitle: "Which step comes next?",
    deleteStep: "Delete step",
    emptyTitle: "Pick a step on the map",
    emptyBody: "Here you name it, choose its offer, open its page and decide where the shopper goes next.",

    // Generic pages.
    pagesTitle: "Other pages",
    pagesHint: "Contact, about, policies — off the map. Link to them from any page.",
    pagesShow: "Show other pages",
    pagesHide: "Hide other pages",
    pagesAdd: "Add page",
    pagesEmpty: "No other pages yet.",
    contact: "Contact us",
    about: "About us",
    policies: "Policies",
    blank: "Blank page",
    contactWhy: "Phone, WhatsApp and a form",
    aboutWhy: "Your story, in your words",
    policiesWhy: "Shipping, returns, privacy",
    blankWhy: "Start from nothing",
    pageMenu: "Actions for {name}",
    copyLink: "Copy the link",
    copied: "Link copied: {path}",
    unsaved: "Save the funnel to give it a link",
    contactBody: "Write how customers can reach you: phone, WhatsApp, email and working hours.",
    aboutBody: "Tell your story: who you are, what you sell and why customers trust you.",
    policiesBody: "Write your shipping, returns and privacy policies here.",
    blankBody: "",
  },
  ar: {
    steps: "الخطوات",
    addStep: "إضافة خطوة",
    addStepTitle: "أي خطوة تريد إضافتها؟",
    addStepHint: "تُضاف بعد الخطوة المحددة، أو في آخر مسار البيع.",
    collapse: "إخفاء قائمة الخطوات",
    reorder: "تحريك {name} في القائمة",
    rowMenu: "إجراءات {name}",
    openPage: "فتح الصفحة",
    rename: "تغيير الاسم",
    duplicate: "إنشاء نسخة",
    remove: "حذف",
    toFix: "{n} تحتاج إلى إصلاح",
    noSteps: "لا توجد خطوات بعد. أضف أول خطوة، أو اختر قالبًا من الخريطة.",
    reorderNote: "السحب هنا يغيّر ترتيب القائمة فقط. طريق العميل هو الأسهم الموجودة على الخريطة.",
    reorderNoteOk: "حسنًا",

    stepSettings: "إعدادات الخطوة",
    close: "إغلاق إعدادات الخطوة",
    problems: "أصلح هذه قبل النشر",
    name: "الاسم",
    nameEmpty: "اكتب اسمًا للخطوة لتميّزها عن غيرها.",
    key: "رمز الخطوة",
    copyKey: "نسخ رمز الخطوة",
    type: "النوع",
    typeTitle: "تغيير نوع الخطوة",
    typeHint: "تبقى الصفحة والطرق الخارجة منها كما هي.",
    offer: "العرض",
    product: "المنتج",
    pickProduct: "اختر منتجًا",
    offerLabel: "العرض",
    pickOffer: "اختر عرضًا",
    noOffers: "هذا المنتج ليس له عرض مفعّل. أضف عرضًا من صفحة المنتج.",
    noProducts: "لا توجد منتجات بعد. أضف منتجًا وعرضًا أولًا.",
    offersError: "تعذّر تحميل العروض. تحقق من الاتصال وافتح الخطوة مرة أخرى.",
    offersLoading: "جارٍ تحميل العروض…",
    required: "مطلوب قبل النشر.",
    offerMissing: "العرض غير موجود أو متوقف. اختر عرضًا آخر.",
    offerPrice: "سعر العرض",
    offerPriceNone: "يأخذ أسعار الخيارات",
    bump: "العرض الإضافي عند الدفع",
    bumpHint: "اختياري. يظهر كخانة «أضف لطلبك» في نموذج هذه الخطوة ويُضاف إلى الطلب نفسه.",
    bumpLabel: "العرض الإضافي",
    after: "بعد هذه الخطوة",
    afterHint: "إلى أين ينتقل العميل بعد ذلك.",
    addWay: "إضافة طريق",
    noWays: "لا يوجد طريق خارج بعد. أضف طريقًا، وإلا توقف مسار البيع هنا.",
    thankYouEnds: "صفحة الشكر هي آخر مسار البيع.",
    needOtherStep: "أضف خطوة أخرى أولًا ثم اربطها بهذه.",
    wayWhen: "متى",
    wayTo: "ينتقل إلى",
    wayToOption: "{name}",
    wayGone: "حُذفت هذه الخطوة. اختر خطوة أخرى.",
    pickStep: "اختر خطوة",
    removeWay: "إزالة هذا الطريق",
    priority: "الأولوية",
    priorityHint: "إذا انطبق طريقان معًا، يُنفَّذ صاحب الرقم الأعلى.",
    otherConditions: "شروط أخرى",
    sameCondition: "يوجد طريقان بالشرط نفسه. سيسلك العميل صاحب الأولوية الأعلى.",
    noDecline: "لا يوجد طريق للعميل الذي يرفض. أضف طريقًا، وإلا توقف هنا.",
    noAccept: "لا يوجد طريق للعميل الذي يوافق. أضف طريقًا، وإلا توقف هنا.",
    whenButton: "عند الضغط على الزر «{label}»",
    page: "الصفحة",
    pageEmpty: "الصفحة فارغة. أضف إليها محتوى قبل النشر.",
    pageCount: "{sections} · {elements}",
    section_one: "قسم واحد",
    section_two: "قسمان",
    section_few: "{n} أقسام",
    section_other: "{n} قسمًا",
    element_one: "عنصر واحد",
    element_two: "عنصران",
    element_few: "{n} عناصر",
    element_other: "{n} عنصرًا",
    testRunning: "اختبار يعمل على هذه الخطوة",
    testNamed: "«{name}» يعرض نسختين من هذه الصفحة.",
    openTests: "فتح الاختبارات",
    addNext: "إضافة الخطوة التالية",
    addNextTitle: "أي خطوة تأتي بعدها؟",
    deleteStep: "حذف الخطوة",
    emptyTitle: "اختر خطوة من الخريطة",
    emptyBody: "هنا تسمّيها، وتختار عرضها، وتفتح صفحتها، وتحدد إلى أين ينتقل العميل بعدها.",

    pagesTitle: "صفحات أخرى",
    pagesHint: "تواصل معنا، من نحن، السياسات — خارج الخريطة. اربطها من أي صفحة.",
    pagesShow: "عرض الصفحات الأخرى",
    pagesHide: "إخفاء الصفحات الأخرى",
    pagesAdd: "إضافة صفحة",
    pagesEmpty: "لا توجد صفحات أخرى بعد.",
    contact: "تواصل معنا",
    about: "من نحن",
    policies: "السياسات",
    blank: "صفحة فارغة",
    contactWhy: "هاتف وواتساب ونموذج",
    aboutWhy: "قصتك بكلماتك",
    policiesWhy: "الشحن والاسترجاع والخصوصية",
    blankWhy: "ابدأ من الصفر",
    pageMenu: "إجراءات {name}",
    copyLink: "نسخ الرابط",
    copied: "نُسخ الرابط: {path}",
    unsaved: "احفظ مسار البيع لتحصل الصفحة على رابط",
    contactBody: "اكتب كيف يصل إليك العملاء: الهاتف، واتساب، البريد الإلكتروني ومواعيد العمل.",
    aboutBody: "اروِ قصتك: من أنت، ماذا تبيع، ولماذا يثق بك العملاء.",
    policiesBody: "اكتب هنا سياسات الشحن والاسترجاع والخصوصية.",
    blankBody: "",
  },
} satisfies Messages;

/** One line saying what each step type is for (the "Add step" menu and the type picker). */
export const STEP_TYPE_PURPOSE: Record<Locale, Record<UiStepType, string>> = {
  en: {
    article: "A story that warms the shopper up before the offer",
    landing: "The first thing a shopper sees",
    sales: "Sells the product and takes the order on the page",
    opt_in: "Takes a name and a number before they go on",
    checkout: "The order form: details, then confirm",
    upsell: "One more thing, offered right after the order",
    downsell: "A smaller offer for a shopper who said no",
    thank_you: "The last page, after the order",
    custom: "A free page you build as you like",
  },
  ar: {
    article: "قصة تهيّئ العميل قبل أن يرى العرض",
    landing: "أول ما يراه العميل",
    sales: "تقنعه بالمنتج ويُرسل منها الطلب",
    opt_in: "تأخذ اسمه ورقمه قبل أن يكمل",
    checkout: "نموذج الطلب: يكتب بياناته ويؤكد",
    upsell: "عرض إضافي يظهر له بعد أن يطلب",
    downsell: "عرض أصغر لمن رفض العرض السابق",
    thank_you: "آخر صفحة، بعد الطلب",
    custom: "صفحة حرة تبنيها كما تشاء",
  },
};

/** A way out's condition as the sentence it is: "when does the shopper take this path?" */
export const CONDITION_WORDS: Record<Locale, Record<UiEdgeCondition, string>> = {
  en: {
    always: "Always",
    completed_checkout: "After they order",
    accepted_offer: "If they take the offer",
    declined_offer: "If they say no",
    clicked_through: "When they press a button",
  },
  ar: {
    always: "دائمًا",
    completed_checkout: "بعد أن يطلب",
    accepted_offer: "إذا وافق على العرض",
    declined_offer: "إذا رفض",
    clicked_through: "عند الضغط على زر",
  },
};

/**
 * The conditions that mean something on each step type, most likely first
 * (what the storefront really sends from that kind of step). The rest stay
 * reachable under "Other conditions": the backend accepts any of them.
 */
export const SENSIBLE_CONDITIONS: Record<UiStepType, UiEdgeCondition[]> = {
  article: ["clicked_through", "always"],
  landing: ["clicked_through", "always"],
  sales: ["completed_checkout", "clicked_through", "always"],
  opt_in: ["clicked_through", "always"],
  checkout: ["completed_checkout", "always"],
  upsell: ["accepted_offer", "declined_offer", "always"],
  downsell: ["accepted_offer", "declined_offer", "always"],
  thank_you: ["always"],
  custom: ["clicked_through", "always"],
};
